//! XOR-JIT GF(2^16) multiply tier for pre-GFNI x86.
//!
//! Runtime-dispatched when AVX2 is present but GFNI is not. Reconstruction
//! multiply is JIT-generated as bit-plane XOR sequences, which run on the four
//! vector-ALU ports instead of the two shuffle ports that bound the shuffle2x
//! tier.
//!
//! Build order (each phase validated before the next):
//! 1. [`emit`] — the x86-64 machine-code emitter (byte-exact unit tests).
//! 2. `memory` — W^X executable buffers.
//! 3. `transpose` — the 16-plane bit-transpose prepare/finish.
//! 4. `deps` + `codegen` — factor -> vpxor schedule.

mod avx2_emitter;
pub mod codegen;
pub mod deps;
pub mod emit;
pub mod memory;
pub mod packed;
pub mod transpose;

/// JIT tier width. Only the AVX2 512-byte-block tier exists: the AVX-512
/// JIT was removed after c5 hardware measurement — the oracle never
/// default-selects an XOR-JIT above the AVX2 line, and 512-bit shuffle beats
/// it on the only silicon that could run it (git history preserves the
/// implementation). The enum stays so width-generic consumers keep their
/// shape.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum JitWidth {
    Avx2,
}

impl JitWidth {
    /// Select the default XOR-JIT method.
    ///
    /// The AVX2 tier is selected only on CPUs marked as fast for JIT, after
    /// rejecting binary translation and GFNI-capable machines. Other CPU
    /// methods remain the controller's fallback.
    pub fn detect() -> Option<JitWidth> {
        if supported() && fast_jit_cpu() {
            Some(JitWidth::Avx2)
        } else {
            None
        }
    }

    /// Planar block size this width consumes.
    pub const fn block_bytes(self) -> usize {
        match self {
            JitWidth::Avx2 => transpose::BLOCK_BYTES,
        }
    }

    /// Build the JIT'd muladd body for `factor` (None for factor 0).
    pub fn build_muladd(self, factor: u16) -> std::io::Result<Option<memory::JitCode>> {
        match self {
            JitWidth::Avx2 => build_muladd(factor),
        }
    }

    /// Build several coefficient bodies in one immutable executable arena.
    /// The arena is writable only while generated bytes are copied, then is
    /// finalized read+execute once before any returned body can run.
    pub fn build_muladd_batch(
        self,
        factors: &[u16],
    ) -> std::io::Result<Vec<Option<memory::JitCode>>> {
        let generated = factors
            .iter()
            .copied()
            .filter(|&factor| factor != 0)
            .map(|factor| match self {
                JitWidth::Avx2 => generate_avx2_body(factor, false),
            })
            .collect::<std::io::Result<Vec<_>>>()?;
        let mut built = memory::JitCode::new_batch(&generated)?.into_iter();
        let result = factors
            .iter()
            .map(|&factor| (factor != 0).then(|| built.next().expect("one body per factor")))
            .collect();
        debug_assert!(built.next().is_none());
        Ok(result)
    }

    /// Build packed dispatch for one coefficient row. AVX2 uses ordered
    /// single-source bodies; AVX512 uses six-source multi-input bodies with
    /// prefix variants for short final groups.
    pub fn build_packed(self, factors: &[u16]) -> std::io::Result<packed::PackedJitCode> {
        packed::PackedJitCode::new(self, factors)
    }

    /// Estimate one shared packed arena for all output coefficient rows.
    ///
    /// The `JitMemo` owner should call this once per input batch, before
    /// shaping repair buffers, and use the result to select folded fallback
    /// when the arena exceeds its resource budget.
    pub fn estimate_packed_batch(
        self,
        rows: &[&[u16]],
    ) -> Result<packed::PackedCodeSize, packed::PackedBuildError> {
        packed::PackedJitBatch::estimate(self, rows)
    }

    /// Build one shared W^X arena for all output coefficient rows. Retain the
    /// returned batch and select each output with [`packed::PackedJitBatch::row`].
    /// Do not build one [`packed::PackedJitCode`] per output.
    pub fn build_packed_batch(
        self,
        rows: &[&[u16]],
    ) -> Result<packed::PackedJitBatch, packed::PackedBuildError> {
        packed::PackedJitBatch::new(self, rows)
    }

    /// Build a shared packed arena only when its alignment-inclusive code size
    /// is within `limit_bytes`; callers can choose folded fallback on error.
    pub fn build_packed_batch_with_limit(
        self,
        rows: &[&[u16]],
        limit_bytes: usize,
    ) -> Result<packed::PackedJitBatch, packed::PackedBuildError> {
        packed::PackedJitBatch::new_with_limit(self, rows, limit_bytes)
    }

    /// Transpose one block (`block_bytes` long) into planar layout.
    ///
    /// # Safety
    /// AVX2 required; slice lengths must equal [`Self::block_bytes`].
    pub unsafe fn prepare_block(self, src: &[u8], dst: &mut [u8]) {
        unsafe {
            match self {
                JitWidth::Avx2 => transpose::prepare_block(
                    src.first_chunk().expect("src block size"),
                    dst.first_chunk_mut().expect("dst block size"),
                ),
            }
        }
    }

    /// Invert [`Self::prepare_block`] in place.
    ///
    /// # Safety
    /// AVX2 required; `buf` length must equal [`Self::block_bytes`].
    pub unsafe fn finish_block(self, buf: &mut [u8]) {
        unsafe {
            match self {
                JitWidth::Avx2 => {
                    transpose::finish_block(buf.first_chunk_mut().expect("block size"))
                }
            }
        }
    }

    /// Run a muladd body built by [`Self::build_muladd`] over `len` planar
    /// bytes (`len % block_bytes == 0`).
    ///
    /// # Safety
    /// `code` must have been built by [`Self::build_muladd`] for this exact
    /// width, and that width's CPU features must be available. `src` must be
    /// readable and `dst` writable for `len` non-overlapping bytes. `len` must
    /// be a multiple of [`Self::block_bytes`].
    pub unsafe fn run_muladd(
        self,
        code: &memory::JitCode,
        src: *const u8,
        dst: *mut u8,
        len: usize,
    ) {
        unsafe {
            match self {
                JitWidth::Avx2 => code.run_muladd(src, dst, len),
            }
        }
    }

    /// Build a single-factor body with a dedicated RSI prefetch stream.
    pub fn build_muladd_prefetch(self, factor: u16) -> std::io::Result<Option<memory::JitCode>> {
        if factor == 0 {
            return Ok(None);
        }
        let code = match self {
            JitWidth::Avx2 => generate_avx2_body(factor, true)?,
        };
        Ok(Some(memory::JitCode::new(&code)?))
    }

    /// Run a prefetch-enabled single-factor body. The body must have been
    /// created by [`Self::build_muladd_prefetch`].
    ///
    /// # Safety
    /// `code` must have been built by [`Self::build_muladd_prefetch`] for this
    /// exact width, and that width's CPU features must be available. `src`
    /// must be readable and `dst` writable for `len` non-overlapping bytes;
    /// `len` must be a multiple of [`Self::block_bytes`]. `prefetch` must
    /// support every address hinted by the selected width's prefetch stream.
    pub unsafe fn run_muladd_prefetch(
        self,
        code: &memory::JitCode,
        src: *const u8,
        dst: *mut u8,
        len: usize,
        prefetch: *const u8,
    ) {
        unsafe {
            match self {
                JitWidth::Avx2 => code.run_muladd_prefetch(src, dst, len, prefetch),
            }
        }
    }

    /// Run packed multiply-add with optional input/output prefetch hints.
    /// Coefficient rows containing only one use the packed add shortcut.
    ///
    /// # Safety
    /// `code` must have been built for this exact width, which must be
    /// available on the current CPU. The caller must satisfy the pointer,
    /// length, region-count, non-overlap, and prefetch requirements of
    /// [`packed::PackedJitCode::run`]. `scratch` must remain worker-exclusive.
    pub unsafe fn run_packed(
        self,
        code: &packed::PackedJitCode,
        scratch: &mut packed::PackedScratch,
        run: packed::PackedRun,
    ) -> Result<(), packed::PackedExecutionError> {
        unsafe { self.try_run_packed(code, scratch, run) }
    }

    /// Fallible packed dispatch for repair controllers. A returned error means
    /// the caller must discard any staged output touched by this operation.
    ///
    /// # Safety
    /// The caller must satisfy all requirements of [`Self::run_packed`].
    pub unsafe fn try_run_packed(
        self,
        code: &packed::PackedJitCode,
        scratch: &mut packed::PackedScratch,
        run: packed::PackedRun,
    ) -> Result<(), packed::PackedExecutionError> {
        debug_assert_eq!(self, code.width());
        unsafe { code.try_run_with_scratch(scratch, run) }
    }
}

/// Whether the AVX2 XOR-JIT method is available: AVX2 present, GFNI absent,
/// strict W^X available, and not running under binary translation.
///
/// An x86_64 binary running under Rosetta 2 on Apple Silicon must not select
/// this tier: generated x86 would otherwise be translated again for every
/// execution.
pub fn supported() -> bool {
    std::is_x86_feature_detected!("avx2")
        && !std::is_x86_feature_detected!("gfni")
        && !running_translated()
        && strict_wx_available()
}

/// CPU-family gate for the AVX2 JIT. The encoded family calculation keeps the
/// base family in the low nibble and extended family in the upper nibble.
fn fast_jit_cpu() -> bool {
    static FAST: std::sync::OnceLock<bool> = std::sync::OnceLock::new();
    *FAST.get_or_init(|| {
        let info = std::arch::x86_64::__cpuid(1);
        fast_jit_family(encoded_cpu_family(info.eax))
    })
}

const fn encoded_cpu_family(eax: u32) -> u32 {
    ((eax >> 8) & 0x0f) + ((eax >> 16) & 0x0ff0)
}

const fn fast_jit_family(family: u32) -> bool {
    matches!(family, 0x6f | 0x7f | 0x8f | 0xaf)
}

const fn emulated_cpu_vendor(ebx: u32, edx: u32, ecx: u32) -> bool {
    matches!(
        (ebx, edx, ecx),
        // "Virtual CPU "
        (0x7472_6956, 0x206c_6175, 0x2055_5043)
            // "MicrosoftXTA"
            | (0x7263_694d, 0x666f_736f, 0x4154_5874)
            // "VirtualApple"
            | (0x7472_6956, 0x416c_6175, 0x656c_7070)
    )
}

/// Whether this process can perform the strict RW -> RX -> RW transitions
/// required by the worker-local JIT lifecycle.
pub fn strict_wx_available() -> bool {
    static AVAILABLE: std::sync::OnceLock<bool> = std::sync::OnceLock::new();
    *AVAILABLE.get_or_init(|| memory::preflight_wx().is_ok())
}

/// Whether this x86_64 process is executing under binary translation, in which
/// case the JIT tier must not be selected. Detection checks CPUID vendor data,
/// the Windows brand string, and Rosetta process state.
///
/// The result is cached: `supported()` may be called once per batch.
fn running_translated() -> bool {
    static TRANSLATED: std::sync::OnceLock<bool> = std::sync::OnceLock::new();
    *TRANSLATED.get_or_init(|| {
        let vendor = std::arch::x86_64::__cpuid(0);
        if emulated_cpu_vendor(vendor.ebx, vendor.edx, vendor.ecx) {
            return true;
        }

        #[cfg(target_os = "windows")]
        {
            // Windows 11 x64-on-ARM can present an ordinary CPU vendor while
            // identifying the translator in the extended brand string.
            let max_extended = std::arch::x86_64::__cpuid(0x8000_0000).eax;
            if max_extended >= 0x8000_0004 {
                let mut brand = [0u8; 48];
                for (index, leaf) in (0x8000_0002..=0x8000_0004).enumerate() {
                    let words = std::arch::x86_64::__cpuid(leaf);
                    let start = index * 16;
                    brand[start..start + 4].copy_from_slice(&words.eax.to_le_bytes());
                    brand[start + 4..start + 8].copy_from_slice(&words.ebx.to_le_bytes());
                    brand[start + 8..start + 12].copy_from_slice(&words.ecx.to_le_bytes());
                    brand[start + 12..start + 16].copy_from_slice(&words.edx.to_le_bytes());
                }
                if brand
                    .windows(b"Virtual CPU".len())
                    .any(|part| part == b"Virtual CPU")
                {
                    return true;
                }
            }
        }

        #[cfg(target_os = "macos")]
        {
            use std::os::raw::{c_char, c_int, c_void};

            // sysctlbyname(3) — declared locally so this crate keeps its
            // dependency-free surface (no libc). Read-only query, so newp/newlen
            // are null/0. Ref: Apple "About the Rosetta Translation Environment".
            unsafe extern "C" {
                fn sysctlbyname(
                    name: *const c_char,
                    oldp: *mut c_void,
                    oldlenp: *mut usize,
                    newp: *mut c_void,
                    newlen: usize,
                ) -> c_int;
            }

            let mut translated: c_int = 0;
            let mut size = std::mem::size_of::<c_int>();
            // NUL-terminated key name required by sysctlbyname.
            let name = c"sysctl.proc_translated";
            // SAFETY: `name` is a valid NUL-terminated C string; `oldp`/`oldlenp`
            // point at `translated` and its byte length; the query is read-only.
            let rc = unsafe {
                sysctlbyname(
                    name.as_ptr(),
                    (&raw mut translated).cast::<c_void>(),
                    &raw mut size,
                    std::ptr::null_mut(),
                    0,
                )
            };
            // A non-zero return (ENOENT on a genuine pre-Rosetta Intel Mac, where
            // the key does not exist) means "not translated"; only
            // proc_translated == 1 signals a Rosetta 2 (translated) process.
            rc == 0 && translated == 1
        }

        #[cfg(not(target_os = "macos"))]
        false
    })
}

/// Build the JIT'd muladd code for `factor` (returns `None` for factor 0, which
/// contributes nothing). `Err` if executable memory could not be allocated —
/// callers fall back to the shuffle2x tier.
pub fn build_muladd(factor: u16) -> std::io::Result<Option<memory::JitCode>> {
    if factor == 0 {
        return Ok(None);
    }
    let code = generate_avx2_body(factor, false)?;
    Ok(Some(memory::JitCode::new(&code)?))
}

fn generate_avx2_body(factor: u16, prefetch: bool) -> std::io::Result<Vec<u8>> {
    let mut code = Vec::with_capacity(avx2_emitter::MAX_BODY_BYTES);
    avx2_emitter::append_muladd_body(&mut code, factor, prefetch).map_err(std::io::Error::other)?;
    Ok(code)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn running_translated_probe_is_stable() {
        // This module is x86_64-only (see lib.rs), so this test only compiles
        // and runs on an x86_64 build. The probe result depends on the host —
        // an x86_64 test run on Apple Silicon executes under Rosetta 2 and
        // legitimately reports true — so assert the deterministic properties:
        // no panic and a cached/stable answer.
        let first = running_translated();
        assert_eq!(first, running_translated());
    }

    #[test]
    fn default_jit_family_gate_accepts_tuned_families() {
        for family in [0x6f, 0x7f, 0x8f, 0xaf] {
            assert!(fast_jit_family(family));
        }
        for family in [0x06, 0x0f, 0x1f, 0x9f, 0xbf] {
            assert!(!fast_jit_family(family));
        }
        assert_eq!(encoded_cpu_family(0x0080_0f00), 0x8f);
    }

    #[test]
    fn emulation_vendor_gate_recognizes_translators() {
        assert!(emulated_cpu_vendor(0x7472_6956, 0x206c_6175, 0x2055_5043));
        assert!(emulated_cpu_vendor(0x7263_694d, 0x666f_736f, 0x4154_5874));
        assert!(emulated_cpu_vendor(0x7472_6956, 0x416c_6175, 0x656c_7070));
        assert!(!emulated_cpu_vendor(0x6874_7541, 0x6974_6e65, 0x444d_4163));
    }

    #[test]
    fn batched_arena_executes_the_same_body_as_an_individual_mapping() {
        if !std::is_x86_feature_detected!("avx2") {
            return;
        }
        let width = JitWidth::Avx2;
        let factor = 0x5a3c;
        let individual = width.build_muladd(factor).unwrap().unwrap();
        let mut batch = width.build_muladd_batch(&[factor]).unwrap();
        let batched = batch.pop().unwrap().unwrap();

        let source: Vec<u8> = (0..width.block_bytes())
            .map(|index| (index as u8).wrapping_mul(29).wrapping_add(7))
            .collect();
        let mut packed = vec![0u8; width.block_bytes()];
        let mut expected = vec![0u8; width.block_bytes()];
        let mut actual = vec![0u8; width.block_bytes()];
        unsafe {
            width.prepare_block(&source, &mut packed);
            width.run_muladd(
                &individual,
                packed.as_ptr(),
                expected.as_mut_ptr(),
                packed.len(),
            );
            width.run_muladd(&batched, packed.as_ptr(), actual.as_mut_ptr(), packed.len());
        }
        assert_eq!(actual, expected);
    }
}
