#!/bin/bash
# Regenerate the stored-layout fixture sets consumed by
# tests/stored_layout_fixtures.rs, plus the multi-member multi-volume sets
# tests/integration.rs uses for volume addressing.
#
# These sets exist because the rest of the corpus does not reach them: a chain
# longer than twenty volumes, a recovery record on every volume of a stored
# set, the `-htb` BLAKE2 hash switch, a `-p` encrypted stored set holding more
# than one member, and its plain and solid twins — the only sets here whose
# second member starts past the set's first volume. Everything else those tests
# use is already checked in and generated by the sibling scripts.
#
# Requirements:
# - docker on PATH, with the toolchain images built
#   (`cargo run --locked -p xtask -- bench toolchains build`): the writer is
#   the rarlab-7.20 image from bench/rarpar-bench/config/toolchains.json —
#   RARLAB rar 7.20, with `rar` as ENTRYPOINT. Note that 7.20 dropped `-ma4`
#   and `-vn`, so it cannot write RAR4 archives or old-style (.r00) volume
#   names; the RAR4 sets come from the rarlab-6.24 image via
#   generate_edge_cases.sh.
#
# Usage: bash crates/unrar-rs/tests/fixtures/generate_stored_layout.sh
#
# Output is not byte-reproducible: RAR stamps archive and file times into the
# headers. The header *shapes* the tests assert are stable.
set -euo pipefail

FIXTURE_DIR="$(cd "$(dirname "$0")" && pwd)"
RAR5_DIR="$FIXTURE_DIR/rar5"
# Same corpus-wide test password as generate_encrypted.sh.
ENC_PASSWORD="testpass123"
WORK="$(mktemp -d)"
cleanup() { rm -rf "$WORK"; }
trap cleanup EXIT

mkdir -p "$WORK/src" "$WORK/out" "$RAR5_DIR"

# Fixed-seed incompressible payloads. Stored members must not be shrinkable, or
# `-m0` stops being the interesting case, and fixed seeds keep the member sizes
# and split boundaries stable across regenerations.
python3 - "$WORK/src" <<'PY'
import os, random, sys
d = sys.argv[1]
def blob(name, size, seed):
    r = random.Random(seed)
    with open(os.path.join(d, name), 'wb') as f:
        f.write(bytes(r.randrange(256) for _ in range(size)))
blob('Silver.Horizon.S01E04.mkv', 48 * 1024, 4004)
blob('Silver.Horizon.S01E05.mkv', 16 * 1024, 5005)
blob('Silver.Horizon.S01E06.mkv', 4 * 1024, 6006)
blob('Silver.Horizon.S01E07.mkv', 3 * 1024, 7007)
# Encrypted-store payloads. AES-CBC pads the member's plaintext up to a whole
# block, so the two sizes are chosen to sit on opposite sides of that: 20001 is
# 15 bytes short of a block boundary and 12288 is exactly on one. A set holding
# both proves `align16` in the same archive as the case where it is a no-op.
blob('Silver.Horizon.S02E01.mkv', 20001, 2101)
blob('Silver.Horizon.S02E02.mkv', 12 * 1024, 2102)
with open(os.path.join(d, 'Silver.Horizon.S01E07.nfo'), 'w') as f:
    f.write('Silver Horizon season one, episode seven.\n')
PY

# Image tag as pinned in bench/rarpar-bench/config/toolchains.json.
RAR5_IMAGE="rarpar-bench-rarlab:7.20"

rar5() {
    docker run --rm --platform linux/amd64 -v "$WORK:/w" -w /w/src "$RAR5_IMAGE" "$@"
}

# [1/7] Long chain: 48 KiB across 2 KiB volumes -> 27 parts. The first part is
# one byte larger than the middle ones and the last is much smaller, so a
# prefix sum over the chain cannot be mistaken for `index * part_size`.
rar5 a -idq -m0 -v2k ../out/rar5_mv_store_long.rar Silver.Horizon.S01E04.mkv

# [2/7] Recovery record on every volume of a stored multi-volume set: RR
# service data that must land in the envelope without disturbing the member
# mapping. 16 KiB across 4 KiB volumes -> 6 parts.
rar5 a -idq -m0 -rr5p -v4k ../out/rar5_mv_store_rr.rar Silver.Horizon.S01E05.mkv

# [3/7] BLAKE2 across a split chain: non-final parts state a packed BLAKE2sp
# and no packed CRC32. 4 KiB across 1 KiB volumes -> 6 parts.
rar5 a -idq -m0 -htb -v1k ../out/rar5_mv_store_blake2.rar Silver.Horizon.S01E06.mkv

# [4/7] and [5/7] The BLAKE2 pair: identical members and layout, differing only
# in the hash switch. Together they establish that `-htb` replaces the CRC32
# rather than adding to it.
rar5 a -idq -m0 -htb ../out/rar5_store_blake2.rar \
    Silver.Horizon.S01E07.mkv Silver.Horizon.S01E07.nfo
rar5 a -idq -m0 ../out/rar5_store_crc32_control.rar \
    Silver.Horizon.S01E07.mkv Silver.Horizon.S01E07.nfo

# [6/9] and [7/9] Encrypted (`-p`) stored sets — file data encrypted, headers
# plain — holding the same two members, once split across volumes and once in a
# single volume. `-p` is the direct-store case: the header chain parses without
# the password, so the layout classifies the set before anything is decrypted.
# Two members mean two independent CBC chains (RAR states a per-member IV) and
# a volume that carries the tail of one member and the head of the next.
# 20001 + 12288 payload bytes across 4 KiB volumes -> 9 parts.
rar5 a -idq -m0 -p"$ENC_PASSWORD" -v4k ../out/rar5_enc_mv_store_pair.rar \
    Silver.Horizon.S02E01.mkv Silver.Horizon.S02E02.mkv
rar5 a -idq -m0 -p"$ENC_PASSWORD" ../out/rar5_enc_store_pair.rar \
    Silver.Horizon.S02E01.mkv Silver.Horizon.S02E02.mkv

# [8/9] and [9/9] The plain and solid twins of the encrypted pair: the same two
# members and the same 4 KiB volumes, so the second member again begins in the
# set's sixth volume. They are what the streaming extraction paths are held to
# for volume addressing — every other multi-volume set in the corpus holds one
# member starting in volume 0, where a member-relative and a set-absolute
# numbering are the same numbering. `-s` adds the case where reaching the second
# member has to decode the first, addressing its volumes too.
rar5 a -idq -m0 -v4k ../out/rar5_mv_store_pair.rar \
    Silver.Horizon.S02E01.mkv Silver.Horizon.S02E02.mkv
rar5 a -idq -m5 -s -v4k ../out/rar5_mv_solid_pair.rar \
    Silver.Horizon.S02E01.mkv Silver.Horizon.S02E02.mkv

rm -f "$RAR5_DIR"/rar5_mv_store_long.part*.rar \
      "$RAR5_DIR"/rar5_mv_store_rr.part*.rar \
      "$RAR5_DIR"/rar5_mv_store_blake2.part*.rar \
      "$RAR5_DIR"/rar5_store_blake2.rar \
      "$RAR5_DIR"/rar5_store_crc32_control.rar \
      "$RAR5_DIR"/rar5_enc_mv_store_pair.part*.rar \
      "$RAR5_DIR"/rar5_enc_store_pair.rar \
      "$RAR5_DIR"/rar5_mv_store_pair.part*.rar \
      "$RAR5_DIR"/rar5_mv_solid_pair.part*.rar
cp "$WORK"/out/*.rar "$RAR5_DIR/"
chmod 444 "$WORK"/out/*.rar 2>/dev/null || true

echo "Generated stored-layout fixtures into $RAR5_DIR:"
ls -1 "$WORK/out"
