//! PAR-inside for RAR5 archives and RAR5 volume sets.
//!
//! **Experimental.** The region layout is not part of the PAR3 specification
//! yet; it may change before it is stable, and regions written by this version
//! may not verify with a later one.
//!
//! RAR5 framing is read from block headers only: signature, header CRC32,
//! header size, type, flags and data size. Members are never decompressed and
//! no RAR structure is rewritten. Every host file keeps its original bytes in
//! place; the PAR3 carrier occupies one unprotected chunk of the file:
//!
//! - [`Rar5Layout::Trailing`]: after the end-of-archive header (and the zero
//!   padding a non-final volume carries). The archive is untouched.
//! - [`Rar5Layout::Block`]: one header of an unassigned block type with the
//!   skip-if-unknown flag, data area = carrier, placed just before the
//!   end-of-archive header.
//! - [`Rar5Layout::Service`]: one service header named `PAR3` with the
//!   skip-if-unknown flag, data area = carrier, placed the same way.
//!
//! A volume set is one PAR3 input set with one File packet per volume. Every
//! volume carries the whole metadata followed by a contiguous range of
//! Recovery Data packets; ranges are assigned in volume order. Because the
//! layout is fixed by rule, a region can be regenerated byte for byte from
//! the metadata of any other region and the protected data.

use std::collections::{BTreeMap, BTreeSet};
use std::io::{self, BufWriter, Write};
use std::ops::Range;
use std::path::{Path, PathBuf};
use std::sync::Arc;

use crc_fast::{CrcAlgorithm, Digest};

use crate::carrier::{CarrierPlan, CarrierRestoration};
use crate::creation::{
    CreationCodec, CreationDurability, CreationOptions, CreationPlan, CreationSource,
};
use crate::ingest::{AuthenticatingWriter, IngestedPacket, PacketScanner, PayloadKind, ScanEvent};
use crate::runtime::{
    EngineError, EngineFile as File, EngineResult, ExecutionOptions, OpenBudgeted,
};
use crate::session::{Par3RepairSession, RepairStatus};
use crate::source::{DiskSourceAccess, SourceAccess, SourceId, SourceSnapshot, read_exact_at};
use crate::{Fingerprint, FingerprintHasher, InputSetId, ScanLimits};

const SIGNATURE: [u8; 8] = *b"Rar!\x1a\x07\x01\x00";
const SIGNATURE_RAR4: [u8; 7] = *b"Rar!\x1a\x07\x00";
const PACKET_MAGIC: [u8; 8] = *b"PAR3\0PKT";
/// Self-extracting modules precede the signature by at most this much.
const SFX_LIMIT: u64 = 1 << 20;
/// Block type of the [`Rar5Layout::Block`] region header.
pub const REGION_BLOCK_TYPE: u64 = 0x50;
/// Service name of the [`Rar5Layout::Service`] region header.
pub const REGION_SERVICE_NAME: &[u8] = b"PAR3";
const FLAG_EXTRA: u64 = 0x1;
const FLAG_DATA: u64 = 0x2;
const FLAG_SKIP: u64 = 0x4;
/// Recovery Data packet overhead: header 48, root 16, matrix 16, index 8.
const RECOVERY_OVERHEAD: u64 = 88;

/// Where the carrier sits in a RAR5 host.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Rar5Layout {
    /// After the end-of-archive header and any volume padding.
    Trailing,
    /// An unassigned block type with the skip flag, before the end header.
    Block,
    /// A `PAR3` service header with the skip flag, before the end header.
    Service,
}

/// How recovery packets are distributed over the volumes of a set.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Rar5Placement {
    /// One set; every volume holds the metadata and an even share of recovery.
    Spread,
    /// One set; every volume holds the metadata, the last holds all recovery.
    Last,
    /// One set per volume, each with its own recovery.
    Independent,
}

/// Framing facts of one RAR5 host file.
#[derive(Clone, Debug)]
pub struct Rar5Archive {
    /// Offset of the RAR5 signature; nonzero for self-extracting archives.
    pub signature: u64,
    /// Volume number, zero for the first, when the archive is a volume.
    pub volume: Option<u64>,
    /// End header says another volume follows.
    pub more_volumes: bool,
    /// Main header archive flags.
    pub solid: bool,
    /// Archive is locked against modification.
    pub locked: bool,
    /// Main header announces a recovery record.
    pub recovery_record: bool,
    /// Headers are encrypted; nothing after the main signature is walkable.
    pub encrypted_headers: bool,
    /// End-of-archive header, when headers are walkable.
    pub end_header: Option<Range<u64>>,
    /// End of the archive's own bytes, including volume zero padding. For
    /// encrypted headers this is the whole file.
    pub archive_end: u64,
    /// An embedded region already present, with its layout.
    pub region: Option<(Rar5Layout, Range<u64>)>,
    /// Header blocks walked.
    pub blocks: u64,
    /// File length.
    pub length: u64,
}

impl Rar5Archive {
    /// Length of the archive without any embedded region.
    pub fn original_length(&self) -> u64 {
        match &self.region {
            Some((_, range)) => self.length - (range.end - range.start),
            None => self.length,
        }
    }
}

fn read_vint(bytes: &[u8], at: &mut usize) -> EngineResult<u64> {
    let mut value = 0u64;
    for shift in (0..70).step_by(7) {
        let byte = *bytes
            .get(*at)
            .ok_or(EngineError::Unsupported("truncated RAR5 header field"))?;
        *at += 1;
        if shift == 63 && byte > 1 {
            return Err(EngineError::Unsupported("oversized RAR5 header field"));
        }
        value |= u64::from(byte & 0x7f) << shift;
        if byte & 0x80 == 0 {
            return Ok(value);
        }
    }
    Err(EngineError::Unsupported("oversized RAR5 header field"))
}

fn push_vint(out: &mut Vec<u8>, mut value: u64) {
    loop {
        let byte = (value & 0x7f) as u8;
        value >>= 7;
        if value == 0 {
            out.push(byte);
            return;
        }
        out.push(byte | 0x80);
    }
}

fn crc32(bytes: &[u8]) -> u32 {
    let mut crc = Digest::new(CrcAlgorithm::Crc32IsoHdlc);
    crc.update(bytes);
    crc.finalize() as u32
}

/// The bytes that precede a carrier of `carrier` bytes in `layout`.
pub fn region_header(layout: Rar5Layout, carrier: u64) -> Vec<u8> {
    let mut inner = Vec::new();
    match layout {
        Rar5Layout::Trailing => return Vec::new(),
        Rar5Layout::Block => {
            push_vint(&mut inner, REGION_BLOCK_TYPE);
            push_vint(&mut inner, FLAG_DATA | FLAG_SKIP);
            push_vint(&mut inner, carrier);
        }
        Rar5Layout::Service => {
            push_vint(&mut inner, 3);
            push_vint(&mut inner, FLAG_DATA | FLAG_SKIP);
            push_vint(&mut inner, carrier);
            // File flags, unpacked size, attributes, compression (stored),
            // host OS (Unix), name length, name.
            push_vint(&mut inner, 0);
            push_vint(&mut inner, carrier);
            push_vint(&mut inner, 0);
            push_vint(&mut inner, 0);
            push_vint(&mut inner, 1);
            push_vint(&mut inner, REGION_SERVICE_NAME.len() as u64);
            inner.extend_from_slice(REGION_SERVICE_NAME);
        }
    }
    let mut sized = Vec::with_capacity(inner.len() + 3);
    push_vint(&mut sized, inner.len() as u64);
    sized.extend_from_slice(&inner);
    let mut out = crc32(&sized).to_le_bytes().to_vec();
    out.extend_from_slice(&sized);
    out
}

/// Walk a RAR5 host. RAR4 and non-RAR inputs are refused, and so is any
/// trailing data that is neither volume zero padding nor a PAR3 region.
pub fn inspect(
    access: &dyn SourceAccess,
    source: SourceId,
    options: &ExecutionOptions,
) -> EngineResult<Rar5Archive> {
    let snapshot = access.snapshot(source)?.ok_or(EngineError::Unavailable {
        source_id: source,
        offset: 0,
    })?;
    let length = snapshot.len;
    let read = |offset: u64, out: &mut [u8]| -> EngineResult<()> {
        read_exact_at(&options.diagnostics, access, source, offset, out)
    };
    let probe = length.min(SFX_LIMIT + SIGNATURE.len() as u64) as usize;
    let mut head = vec![0; probe];
    read(0, &mut head)?;
    let rar5 = head.windows(SIGNATURE.len()).position(|w| w == SIGNATURE);
    let rar4 = head
        .windows(SIGNATURE_RAR4.len())
        .position(|w| w == SIGNATURE_RAR4);
    let signature = match (rar5, rar4) {
        (Some(at), Some(old)) if old < at => {
            return Err(EngineError::Unsupported("RAR4 archives are not supported"));
        }
        (Some(at), _) => at as u64,
        (None, Some(_)) => return Err(EngineError::Unsupported("RAR4 archives are not supported")),
        (None, None) => return Err(EngineError::Unsupported("not a RAR5 archive")),
    };
    drop(head);
    let mut archive = Rar5Archive {
        signature,
        volume: None,
        more_volumes: false,
        solid: false,
        locked: false,
        recovery_record: false,
        encrypted_headers: false,
        end_header: None,
        archive_end: length,
        region: None,
        blocks: 0,
        length,
    };
    let mut at = signature + SIGNATURE.len() as u64;
    let mut header = Vec::new();
    loop {
        options.cancel.check()?;
        let mut lead = [0u8; 7];
        let avail = (length.saturating_sub(at)).min(7) as usize;
        if avail < 5 {
            return Err(EngineError::Unsupported("RAR5 archive has no end header"));
        }
        read(at, &mut lead[..avail])?;
        let mut cursor = 4;
        let size = read_vint(&lead[..avail], &mut cursor)?;
        if cursor > 7 || size == 0 || size > 2 << 20 {
            return Err(EngineError::Unsupported("RAR5 header size"));
        }
        let header_end = at + cursor as u64 + size;
        if header_end > length {
            return Err(EngineError::Unsupported("truncated RAR5 header"));
        }
        header.resize((header_end - at) as usize, 0);
        read(at, &mut header)?;
        if crc32(&header[4..]) != u32::from_le_bytes(header[..4].try_into().expect("crc")) {
            return Err(EngineError::Unsupported("RAR5 header CRC mismatch"));
        }
        archive.blocks += 1;
        let mut field = cursor;
        let kind = read_vint(&header, &mut field)?;
        let flags = read_vint(&header, &mut field)?;
        if flags & FLAG_EXTRA != 0 {
            read_vint(&header, &mut field)?;
        }
        let data = if flags & FLAG_DATA != 0 {
            read_vint(&header, &mut field)?
        } else {
            0
        };
        let block_end = header_end
            .checked_add(data)
            .filter(|end| *end <= length)
            .ok_or(EngineError::Unsupported("truncated RAR5 data area"))?;
        match kind {
            1 => {
                let archive_flags = read_vint(&header, &mut field)?;
                if archive_flags & 0x1 != 0 {
                    archive.volume = Some(if archive_flags & 0x2 != 0 {
                        read_vint(&header, &mut field)?
                    } else {
                        0
                    });
                }
                archive.solid = archive_flags & 0x4 != 0;
                archive.recovery_record = archive_flags & 0x8 != 0;
                archive.locked = archive_flags & 0x10 != 0;
            }
            4 => {
                // Everything after this header is encrypted and opaque. The
                // whole file is the archive.
                archive.encrypted_headers = true;
                return Ok(archive);
            }
            5 => {
                let end_flags = read_vint(&header, &mut field)?;
                archive.more_volumes = end_flags & 0x1 != 0;
                archive.end_header = Some(at..header_end);
                break;
            }
            REGION_BLOCK_TYPE if is_region(read, header_end, data)? => {
                set_region(&mut archive, Rar5Layout::Block, at..block_end)?;
            }
            3 if service_name(&header, field)? == REGION_SERVICE_NAME
                && is_region(read, header_end, data)? =>
            {
                set_region(&mut archive, Rar5Layout::Service, at..block_end)?;
            }
            _ => {}
        }
        at = block_end;
    }
    let end = archive.end_header.clone().expect("end header").end;
    // Zero padding may follow the end header of a non-final volume.
    let mut pad = end;
    let mut window = [0u8; 4096];
    while pad < length {
        let take = (length - pad).min(window.len() as u64) as usize;
        read(pad, &mut window[..take])?;
        match window[..take].iter().position(|byte| *byte != 0) {
            Some(first) => {
                pad += first as u64;
                break;
            }
            None => pad += take as u64,
        }
    }
    archive.archive_end = pad;
    if pad < length {
        if !is_region(read, pad, length - pad)? {
            return Err(EngineError::Unsupported(
                "unknown data after the RAR5 end header",
            ));
        }
        set_region(&mut archive, Rar5Layout::Trailing, pad..length)?;
    }
    Ok(archive)
}

fn is_region(
    read: impl Fn(u64, &mut [u8]) -> EngineResult<()>,
    at: u64,
    length: u64,
) -> EngineResult<bool> {
    if length < PACKET_MAGIC.len() as u64 {
        return Ok(false);
    }
    let mut magic = [0u8; 8];
    read(at, &mut magic)?;
    Ok(magic == PACKET_MAGIC)
}

fn set_region(
    archive: &mut Rar5Archive,
    layout: Rar5Layout,
    range: Range<u64>,
) -> EngineResult<()> {
    if archive.region.is_some() {
        return Err(EngineError::Unsupported("more than one PAR3 region"));
    }
    archive.region = Some((layout, range));
    Ok(())
}

fn service_name(header: &[u8], mut field: usize) -> EngineResult<&[u8]> {
    let flags = read_vint(header, &mut field)?;
    read_vint(header, &mut field)?;
    read_vint(header, &mut field)?;
    if flags & 0x2 != 0 {
        field += 4;
    }
    if flags & 0x4 != 0 {
        field += 4;
    }
    read_vint(header, &mut field)?;
    read_vint(header, &mut field)?;
    let length = read_vint(header, &mut field)? as usize;
    header
        .get(field..field + length)
        .ok_or(EngineError::Unsupported("truncated RAR5 service name"))
}

/// One host prepared for insertion.
#[derive(Clone, Debug)]
pub struct Rar5Host {
    /// Existing host file.
    pub path: PathBuf,
    /// Name recorded in the File packet.
    pub name: String,
    /// Framing of the host.
    pub archive: Rar5Archive,
    /// The revision `archive` describes; insertion refuses any other.
    snapshot: SourceSnapshot,
}

/// Bytes added to one host.
#[derive(Clone, Debug)]
pub struct Rar5Inserted {
    /// Output written.
    pub path: PathBuf,
    /// Region bytes, header included.
    pub region_bytes: u64,
    /// Recovery Data packets in the region.
    pub recovery_packets: u64,
    /// Input set the host belongs to.
    pub set: InputSetId,
}

/// Inspect hosts for insertion: every one must be walkable RAR5 without an
/// existing region; volume sets must be complete and in order.
pub fn prepare_hosts(
    paths: &[PathBuf],
    layout: Rar5Layout,
    options: &ExecutionOptions,
) -> EngineResult<Vec<Rar5Host>> {
    if paths.is_empty() {
        return Err(EngineError::InvalidState("insert host count"));
    }
    let disk: Arc<dyn SourceAccess> = Arc::new(disk_access(paths, options));
    let mut hosts = Vec::new();
    for (index, path) in paths.iter().enumerate() {
        let snapshot = disk
            .snapshot(SourceId(index as u64))?
            .ok_or(EngineError::Unavailable {
                source_id: SourceId(index as u64),
                offset: 0,
            })?;
        let archive = inspect(disk.as_ref(), SourceId(index as u64), options)?;
        if disk.snapshot(SourceId(index as u64))? != Some(snapshot) {
            return Err(EngineError::Unsupported(
                "host changed while it was inspected",
            ));
        }
        if archive.region.is_some() {
            return Err(EngineError::Unsupported(
                "archive already holds a PAR3 region",
            ));
        }
        if archive.encrypted_headers {
            if layout != Rar5Layout::Trailing {
                return Err(EngineError::Unsupported(
                    "encrypted RAR5 headers allow only the trailing layout",
                ));
            }
            // The archive cannot be walked, so look for packets directly.
            if !scan(disk.clone(), SourceId(index as u64), 0, options)?.is_empty() {
                return Err(EngineError::Unsupported(
                    "archive already holds PAR3 packets",
                ));
            }
        }
        if archive.locked && layout != Rar5Layout::Trailing {
            return Err(EngineError::Unsupported(
                "a locked RAR5 archive allows only the trailing layout",
            ));
        }
        let name = path
            .file_name()
            .and_then(|name| name.to_str())
            .ok_or(EngineError::Unsupported("host name is not UTF-8"))?
            .to_owned();
        hosts.push(Rar5Host {
            path: path.clone(),
            name,
            archive,
            snapshot,
        });
    }
    // Header-encrypted volumes hide their volume numbers and end flags, so a
    // family missing its last parts cannot be told from a complete one.
    if hosts.iter().any(|host| host.archive.encrypted_headers)
        && (hosts.len() > 1 || hosts.iter().any(|host| looks_like_volume(&host.name)))
    {
        return Err(EngineError::Unsupported(
            "completeness of a header-encrypted RAR5 volume set cannot be checked",
        ));
    }
    let volumes: Vec<_> = hosts.iter().map(|host| host.archive.volume).collect();
    if hosts.len() > 1 || volumes[0].is_some() {
        for (index, host) in hosts.iter().enumerate() {
            let expected_more = index + 1 != hosts.len();
            if host.archive.encrypted_headers {
                continue;
            }
            if host.archive.volume != Some(index as u64)
                || host.archive.more_volumes != expected_more
            {
                return Err(EngineError::Unsupported(
                    "RAR5 volumes are incomplete or out of order",
                ));
            }
        }
    }
    let names: BTreeSet<_> = hosts.iter().map(|host| host.name.as_str()).collect();
    if names.len() != hosts.len() {
        return Err(EngineError::Unsupported("duplicate host names"));
    }
    Ok(hosts)
}

/// A `.partN.rar` name: one volume of a family.
fn looks_like_volume(name: &str) -> bool {
    let lower = name.to_ascii_lowercase();
    lower
        .strip_suffix(".rar")
        .and_then(|stem| stem.rsplit_once(".part"))
        .is_some_and(|(_, digits)| !digits.is_empty() && digits.bytes().all(|b| b.is_ascii_digit()))
}

/// Recovery counts per host of one shared set, for a placement and a total.
///
/// # Errors
///
/// [`EngineError::Unsupported`] for [`Rar5Placement::Independent`], which is
/// one set per host: call [`insert_set`] once per host with that host's own
/// recovery count instead.
pub fn placement_counts(
    placement: Rar5Placement,
    hosts: usize,
    total: u64,
) -> EngineResult<Vec<u64>> {
    if hosts == 0 {
        return Err(EngineError::InvalidState("insert host count"));
    }
    match placement {
        Rar5Placement::Last => {
            let mut counts = vec![0; hosts];
            counts[hosts - 1] = total;
            Ok(counts)
        }
        Rar5Placement::Spread => {
            let base = total / hosts as u64;
            let extra = total % hosts as u64;
            Ok((0..hosts as u64)
                .map(|index| base + u64::from(index < extra))
                .collect())
        }
        Rar5Placement::Independent => Err(EngineError::Unsupported(
            "independent placement inserts one set per host",
        )),
    }
}

/// Insert one set over `hosts`, writing host `k` with its region to
/// `outputs[k]`, which must not exist. `counts[k]` recovery packets go into
/// host `k`; their sum is `options.recovery_count`.
pub fn insert_set(
    hosts: &[Rar5Host],
    outputs: &[PathBuf],
    counts: &[u64],
    layout: Rar5Layout,
    options: CreationOptions,
    scratch_directory: &Path,
    durability: CreationDurability,
) -> EngineResult<Vec<Rar5Inserted>> {
    if options.codec != CreationCodec::Cauchy || options.store_data {
        return Err(EngineError::Unsupported(
            "PAR-inside requires Cauchy recovery without Data packets",
        ));
    }
    if hosts.len() != outputs.len() || hosts.len() != counts.len() || hosts.is_empty() {
        return Err(EngineError::InvalidState("insert host count"));
    }
    // The region records no recovery-index base; opening a set whose
    // recovery packets are all lost assumes zero.
    if options.first_recovery != 0 {
        return Err(EngineError::Unsupported(
            "PAR-inside recovery indices start at zero",
        ));
    }
    let execution = options.execution.clone();
    let mut disk = DiskSourceAccess::with_options(execution.clone());
    for (index, host) in hosts.iter().enumerate() {
        disk.insert(SourceId(index as u64), host.path.clone());
    }
    let disk: Arc<dyn SourceAccess> = Arc::new(disk);
    let mut views = BTreeMap::new();
    let mut sources = Vec::new();
    let mut tails = Vec::new();
    let mut splits = Vec::new();
    for (index, host) in hosts.iter().enumerate() {
        let snapshot = disk
            .snapshot(SourceId(index as u64))?
            .ok_or(EngineError::Unavailable {
                source_id: SourceId(index as u64),
                offset: 0,
            })?;
        // The framing offsets belong to the inspected revision.
        if snapshot != host.snapshot {
            return Err(EngineError::Unsupported(
                "host changed since it was inspected",
            ));
        }
        let split = match layout {
            Rar5Layout::Trailing => host.archive.archive_end,
            _ => {
                host.archive
                    .end_header
                    .as_ref()
                    .ok_or(EngineError::Unsupported("RAR5 end header is required"))?
                    .start
            }
        };
        let body = SourceId(2 * index as u64);
        views.insert(body, (SourceId(index as u64), snapshot, 0..split));
        sources.push(CreationSource {
            name: host.name.clone(),
            source: body,
        });
        let tail = split < snapshot.len;
        if tail {
            let id = SourceId(2 * index as u64 + 1);
            views.insert(id, (SourceId(index as u64), snapshot, split..snapshot.len));
            sources.push(CreationSource {
                name: format!(".rar5-tail-{index}"),
                source: id,
            });
        }
        tails.push(tail);
        splits.push((split, snapshot));
    }
    let views: Arc<dyn SourceAccess> = Arc::new(HostViews {
        access: disk.clone(),
        views,
    });
    let mut plan = CreationPlan::build_in_source_order(views, &sources, options)?;
    let prefix = move |carrier: u64| region_header(layout, carrier).len() as u64;
    let gaps = plan.embedded_set_layout(&tails, counts, &prefix)?;
    for output in outputs {
        if std::fs::symlink_metadata(output).is_ok() {
            return Err(io::Error::new(io::ErrorKind::AlreadyExists, "PAR3 output exists").into());
        }
    }
    let fingerprints = plan.embedded_fingerprints();
    let size = execution.stripe_bytes.min(64 << 10);
    let mut buffer = vec![0; size];
    let mut staged: Vec<PathBuf> = Vec::new();
    let result = (|| -> EngineResult<Vec<Rar5Inserted>> {
        let mut writers = Vec::new();
        let mut copied = Vec::new();
        for (index, output) in outputs.iter().enumerate() {
            let (split, _) = splits[index];
            let source = SourceId(index as u64);
            let (file, cloned) = stage(disk.as_ref(), source, output, &execution, &mut staged)?;
            let mut file = file;
            let mut hash = (!cloned).then(FingerprintHasher::new);
            if cloned {
                file.set_len(split)?;
                io::Seek::seek(&mut file, io::SeekFrom::Start(split))?;
            } else {
                copy(
                    disk.as_ref(),
                    source,
                    0..split,
                    &mut file,
                    &mut buffer,
                    hash.as_mut(),
                    &execution,
                )?;
            }
            copied.push(hash);
            writers.push(BufWriter::with_capacity(
                size,
                AuthenticatingWriter::new(file, plan.input_set_id(), execution.clone()),
            ));
        }
        plan.write_embedded_set(
            &mut writers,
            scratch_directory,
            |index, writer| {
                let header = region_header(layout, gaps[index].1);
                writer.flush()?;
                writer.get_mut().get_mut().write_all(&header)?;
                Ok(())
            },
            |index, writer| {
                writer.flush()?;
                writer.get_ref().finish(gaps[index].1)?;
                Ok(())
            },
        )?;
        let mut reports = Vec::new();
        for (index, writer) in writers.into_iter().enumerate() {
            let mut file = writer
                .into_inner()
                .map_err(io::IntoInnerError::into_error)?
                .into_inner();
            let (split, snapshot) = splits[index];
            let source = SourceId(index as u64);
            let mut hash = copied[index].take();
            copy(
                disk.as_ref(),
                source,
                split..snapshot.len,
                &mut file,
                &mut buffer,
                hash.as_mut(),
                &execution,
            )?;
            crate::source::ensure_snapshot(disk.as_ref(), source, snapshot)?;
            if let Some(hash) = hash
                && hash.finalize() != fingerprints[index]
            {
                return Err(EngineError::InvalidState(
                    "embedded output failed verification",
                ));
            }
            if durability == CreationDurability::SyncFiles {
                file.sync_all()?;
            }
            drop(file);
            std::fs::hard_link(&staged[index], &outputs[index])?;
            reports.push(Rar5Inserted {
                path: outputs[index].clone(),
                region_bytes: gaps[index].0 + gaps[index].1,
                recovery_packets: counts[index],
                set: plan.input_set_id(),
            });
        }
        Ok(reports)
    })();
    for path in staged {
        let _ = std::fs::remove_file(path);
    }
    result
}

fn copy(
    access: &dyn SourceAccess,
    source: SourceId,
    range: Range<u64>,
    out: &mut File,
    buffer: &mut [u8],
    mut hash: Option<&mut FingerprintHasher>,
    options: &ExecutionOptions,
) -> EngineResult<()> {
    let mut at = range.start;
    while at < range.end {
        options.cancel.check()?;
        let take = (range.end - at).min(buffer.len() as u64) as usize;
        read_exact_at(
            &options.diagnostics,
            access,
            source,
            at,
            &mut buffer[..take],
        )?;
        out.write_all(&buffer[..take])?;
        if let Some(hash) = hash.as_deref_mut() {
            hash.update(&buffer[..take]);
        }
        at += take as u64;
    }
    Ok(())
}

/// Stage `destination` as a clone of the source where the filesystem allows,
/// otherwise as an empty file. Records the staging path in `staged`.
fn stage(
    access: &dyn SourceAccess,
    source: SourceId,
    destination: &Path,
    options: &ExecutionOptions,
    staged: &mut Vec<PathBuf>,
) -> EngineResult<(File, bool)> {
    #[cfg(target_os = "macos")]
    if let Some(original) = access.open_file(source)?
        && let Some(temporary) = crate::session_repair::clone_stage_path(destination, &*original.0)?
    {
        staged.push(temporary.clone());
        let output = std::fs::OpenOptions::new()
            .write(true)
            .open_budgeted(&temporary, options)?;
        options.diagnostics.note_clone();
        return Ok((output, true));
    }
    #[cfg(not(target_os = "macos"))]
    let _ = (access, source);
    let temporary = crate::session_repair::stage_path(destination, options)?;
    staged.push(temporary.clone());
    let output = std::fs::OpenOptions::new()
        .write(true)
        .open_budgeted(&temporary, options)?;
    Ok((output, false))
}

/// Install the verified `temporary` at the absent `destination` without
/// replacing anything there. A hard link when both are on one filesystem;
/// across filesystems, a copy staged beside `destination` and compared byte
/// for byte with `temporary` before it is linked into place.
fn install(temporary: &Path, destination: &Path, options: &ExecutionOptions) -> EngineResult<()> {
    match std::fs::hard_link(temporary, destination) {
        Err(error) if error.kind() == io::ErrorKind::CrossesDevices => {
            install_by_copy(temporary, destination, options)
        }
        result => Ok(result?),
    }
}

fn install_by_copy(
    temporary: &Path,
    destination: &Path,
    options: &ExecutionOptions,
) -> EngineResult<()> {
    let staged = crate::session_repair::stage_path(destination, options)?;
    let result = (|| -> EngineResult<()> {
        use std::io::Read;
        let mut from = File::open(temporary, options)?;
        let mut output = std::fs::OpenOptions::new()
            .write(true)
            .truncate(true)
            .open_budgeted(&staged, options)?;
        let length = from.metadata()?.len();
        let size = options.stripe_bytes.clamp(1, 64 << 10);
        let mut buffer = vec![0; size];
        let mut check = vec![0; size];
        let mut at = 0;
        while at < length {
            options.cancel.check()?;
            let take = (length - at).min(size as u64) as usize;
            from.read_exact(&mut buffer[..take])?;
            output.write_all(&buffer[..take])?;
            at += take as u64;
        }
        output.sync_all()?;
        drop((from, output));
        let mut from = File::open(temporary, options)?;
        let mut copied = File::open(&staged, options)?;
        if copied.metadata()?.len() != length {
            return Err(EngineError::InvalidState("installed copy differs"));
        }
        at = 0;
        while at < length {
            options.cancel.check()?;
            let take = (length - at).min(size as u64) as usize;
            from.read_exact(&mut buffer[..take])?;
            copied.read_exact(&mut check[..take])?;
            if buffer[..take] != check[..take] {
                return Err(EngineError::InvalidState("installed copy differs"));
            }
            at += take as u64;
        }
        drop((from, copied));
        std::fs::hard_link(&staged, destination)?;
        Ok(())
    })();
    let _ = std::fs::remove_file(&staged);
    result
}

struct HostViews {
    access: Arc<dyn SourceAccess>,
    views: BTreeMap<SourceId, (SourceId, SourceSnapshot, Range<u64>)>,
}

impl HostViews {
    fn view(&self, source: SourceId) -> io::Result<&(SourceId, SourceSnapshot, Range<u64>)> {
        self.views
            .get(&source)
            .ok_or_else(|| io::Error::new(io::ErrorKind::InvalidInput, "unknown host view"))
    }
}

impl SourceAccess for HostViews {
    fn snapshot(&self, source: SourceId) -> io::Result<Option<SourceSnapshot>> {
        let (host, _, range) = self.view(source)?;
        Ok(self.access.snapshot(*host)?.map(|snapshot| SourceSnapshot {
            len: snapshot.len.min(range.end).saturating_sub(range.start),
            generation: snapshot.generation,
        }))
    }
    fn read_at(&self, source: SourceId, offset: u64, output: &mut [u8]) -> io::Result<usize> {
        let (host, _, range) = self.view(source)?;
        let length = range.end - range.start;
        if offset >= length {
            return Ok(0);
        }
        let take = (length - offset).min(output.len() as u64) as usize;
        self.access
            .read_at(*host, range.start + offset, &mut output[..take])
    }
    fn next_available(&self, source: SourceId, offset: u64) -> io::Result<Option<Range<u64>>> {
        let (host, _, range) = self.view(source)?;
        if offset >= range.end - range.start {
            return Ok(None);
        }
        Ok(self
            .access
            .next_available(*host, range.start + offset)?
            .and_then(|available| {
                let start = available.start.max(range.start);
                let end = available.end.min(range.end);
                (start < end).then_some(start - range.start..end - range.start)
            }))
    }
}

/// Every authenticated packet of any set in `source`, scanning from `from`.
fn scan(
    access: Arc<dyn SourceAccess>,
    source: SourceId,
    from: u64,
    options: &ExecutionOptions,
) -> EngineResult<Vec<IngestedPacket>> {
    let mut scanner = PacketScanner::new(access, source, options.clone(), ScanLimits::default())?;
    if from != 0 {
        scanner.seek(from)?;
    }
    let mut packets = Vec::new();
    loop {
        match scanner.poll()? {
            ScanEvent::Packet(packet) => packets.push(packet),
            ScanEvent::End | ScanEvent::NeedData { .. } => return Ok(packets),
        }
    }
}

/// One host of an opened set.
#[derive(Clone, Debug)]
pub struct Rar5HostState {
    /// Name recorded in the File packet.
    pub name: String,
    /// File currently bound to this host, if any was found.
    pub path: Option<PathBuf>,
    /// How the file was matched to the host.
    pub matched_by: Option<&'static str>,
    /// Index in the set's layout.
    file: usize,
    source: Option<SourceId>,
    /// The unprotected chunk holding the region.
    pub gap: Range<u64>,
    /// Region header bytes at the start of the gap.
    pub prefix: u64,
    /// Expected file length.
    pub length: u64,
    /// Recovery indices this host's region carries.
    pub recovery: Range<u64>,
    /// Protected bytes verified.
    pub complete: bool,
    /// Damaged or missing protected ranges, in file coordinates.
    pub unresolved: Vec<Range<u64>>,
    /// Region packets found at their exact offsets.
    pub packets_found: u64,
    /// Region packets the layout calls for.
    pub packets_expected: u64,
    /// The region, header included, is byte-exact.
    pub region_intact: bool,
}

/// One opened PAR-inside set over RAR5 hosts.
pub struct Rar5Set {
    /// Input set.
    pub id: InputSetId,
    /// Region layout derived from the authenticated gap lengths.
    pub layout: Rar5Layout,
    /// Hosts in set order.
    pub hosts: Vec<Rar5HostState>,
    /// Overall readiness.
    pub status: RepairStatus,
    /// Lost protected blocks.
    pub lost_blocks: u64,
    /// Additional recovery blocks needed when not ready.
    pub additional: u64,
    /// Recovery packets usable now.
    pub recovery_available: u64,
    session: Par3RepairSession,
    metadata: Vec<Vec<u8>>,
    access: Arc<dyn SourceAccess>,
}

fn disk_access(paths: &[PathBuf], options: &ExecutionOptions) -> DiskSourceAccess {
    let mut disk = DiskSourceAccess::with_options(options.clone());
    for (index, path) in paths.iter().enumerate() {
        disk.insert(SourceId(index as u64), path.clone());
    }
    disk
}

struct Candidate {
    path: PathBuf,
    source: SourceId,
    volume: Option<u64>,
    packets: Vec<IngestedPacket>,
}

fn file_name(path: &Path) -> Option<&str> {
    path.file_name().and_then(|name| name.to_str())
}

/// Open every set found in `paths`. Hosts recorded in a set but absent from
/// `paths` are looked up next to the given files under their recorded names
/// and, when the given files were renamed, under the renamed stem.
pub fn open(paths: &[PathBuf], options: &ExecutionOptions) -> EngineResult<Vec<Rar5Set>> {
    let mut known: Vec<PathBuf> = Vec::new();
    for path in paths {
        if !known.contains(path) {
            known.push(path.clone());
        }
    }
    let mut candidates = Vec::new();
    let shared: Arc<dyn SourceAccess> = Arc::new(disk_access(&known, options));
    for (index, path) in known.iter().enumerate() {
        if path.is_file() {
            candidates.push(candidate(
                &shared,
                path.clone(),
                SourceId(index as u64),
                options,
            )?);
        }
    }
    // Names recorded in any set, resolved next to the given files.
    let mut extra = Vec::new();
    for set_names in recorded_names(&candidates, shared, options)? {
        for (name, renamed) in set_names {
            for directory in known.iter().filter_map(|path| path.parent()) {
                for name in [Some(&name), renamed.as_ref()].into_iter().flatten() {
                    let path = directory.join(name);
                    if !known.contains(&path) && !extra.contains(&path) && path.is_file() {
                        extra.push(path);
                    }
                }
            }
        }
    }
    known.extend(extra);
    let access: Arc<dyn SourceAccess> = Arc::new(disk_access(&known, options));
    // Rescan everything through the final provider so packet origins agree.
    let mut candidates = Vec::new();
    for (index, path) in known.iter().enumerate() {
        if path.is_file() {
            candidates.push(candidate(
                &access,
                path.clone(),
                SourceId(index as u64),
                options,
            )?);
        }
    }
    let mut ids: Vec<InputSetId> = Vec::new();
    for candidate in &candidates {
        for packet in &candidate.packets {
            if !ids.contains(&packet.input_set_id()) {
                ids.push(packet.input_set_id());
            }
        }
    }
    if ids.is_empty() {
        return Err(EngineError::Unsupported("no PAR3 packets found"));
    }
    ids.into_iter()
        .map(|id| open_set(id, &candidates, access.clone(), options))
        .collect()
}

fn candidate(
    access: &Arc<dyn SourceAccess>,
    path: PathBuf,
    source: SourceId,
    options: &ExecutionOptions,
) -> EngineResult<Candidate> {
    let archive = inspect(access.as_ref(), source, options).ok();
    let from = archive
        .as_ref()
        .and_then(|archive| archive.region.as_ref().map(|(_, range)| range.start))
        .unwrap_or(0);
    let mut packets = scan(access.clone(), source, from, options)?;
    if packets.is_empty() && from != 0 {
        packets = scan(access.clone(), source, 0, options)?;
    }
    Ok(Candidate {
        path,
        source,
        volume: archive.and_then(|archive| archive.volume),
        packets,
    })
}

/// A recorded host name and, when a sibling was renamed, the name it would
/// have under that sibling's stem.
type RecordedName = (String, Option<String>);

/// Recorded host names per set, each with the name it would have under the
/// stem of a renamed sibling.
fn recorded_names(
    candidates: &[Candidate],
    access: Arc<dyn SourceAccess>,
    options: &ExecutionOptions,
) -> EngineResult<Vec<Vec<RecordedName>>> {
    let mut sessions: BTreeMap<InputSetId, Par3RepairSession> = BTreeMap::new();
    for candidate in candidates {
        for packet in candidate
            .packets
            .iter()
            .filter(|packet| packet.metadata().is_some())
        {
            let id = packet.input_set_id();
            let session = match sessions.entry(id) {
                std::collections::btree_map::Entry::Occupied(entry) => entry.into_mut(),
                std::collections::btree_map::Entry::Vacant(entry) => {
                    entry.insert(Par3RepairSession::new(id, access.clone(), options.clone())?)
                }
            };
            session.merge(packet.clone())?;
        }
    }
    let mut sets = Vec::new();
    for mut session in sessions.into_values() {
        if let Some(layout) = session.layout()? {
            sets.push(
                layout
                    .files()
                    .iter()
                    .map(|file| file.path.clone())
                    .collect::<Vec<_>>(),
            );
        }
    }
    Ok(sets
        .into_iter()
        .map(|names| {
            let renames: Vec<(String, String)> = candidates
                .iter()
                .filter_map(|candidate| file_name(&candidate.path))
                .flat_map(|actual| {
                    names
                        .iter()
                        .filter_map(move |recorded| stem_change(recorded, actual))
                })
                .collect();
            names
                .iter()
                .map(|name| {
                    let renamed = renames.iter().find_map(|(old, new)| {
                        name.strip_prefix(old.as_str())
                            .map(|rest| format!("{new}{rest}"))
                    });
                    (name.clone(), renamed)
                })
                .collect()
        })
        .collect())
}

/// When `recorded` and `actual` differ only before a common suffix that
/// starts at a dot, the old and new stems.
fn stem_change(recorded: &str, actual: &str) -> Option<(String, String)> {
    if recorded == actual {
        return None;
    }
    // Whole characters only: a byte-wise suffix can end inside one.
    let common: usize = recorded
        .chars()
        .rev()
        .zip(actual.chars().rev())
        .take_while(|(a, b)| a == b)
        .map(|(a, _)| a.len_utf8())
        .sum();
    let suffix = &recorded[recorded.len() - common..];
    let dot = suffix.find(".part").or_else(|| suffix.find('.'))?;
    let keep = common - dot;
    let old = &recorded[..recorded.len() - keep];
    let new = &actual[..actual.len() - keep];
    (!old.is_empty() && !new.is_empty()).then(|| (old.to_owned(), new.to_owned()))
}

fn open_set(
    id: InputSetId,
    candidates: &[Candidate],
    access: Arc<dyn SourceAccess>,
    options: &ExecutionOptions,
) -> EngineResult<Rar5Set> {
    let mut session = Par3RepairSession::new(id, access.clone(), options.clone())?;
    for candidate in candidates {
        for packet in candidate.packets.iter().filter(|p| p.input_set_id() == id) {
            session.merge(packet.clone())?;
        }
    }
    let layout = session
        .layout()?
        .ok_or(EngineError::Unsupported("PAR3 metadata is incomplete"))?;
    let block_size = session
        .set()
        .ok_or(EngineError::Unsupported("PAR3 metadata is incomplete"))?
        .block_size();
    let metadata_hashes: BTreeSet<Fingerprint> = session
        .input
        .packets()
        .filter_map(|packet| packet.metadata().map(|metadata| metadata.hash()))
        .collect();
    // Canonical metadata order: the first complete run at the start of a region.
    let mut metadata: Option<Vec<Vec<u8>>> = None;
    for candidate in candidates {
        let mut packets: Vec<&IngestedPacket> = candidate
            .packets
            .iter()
            .filter(|packet| packet.input_set_id() == id)
            .collect();
        packets.sort_by_key(|packet| packet.origin().offset);
        let mut run = Vec::new();
        let mut seen = BTreeSet::new();
        let mut next = None;
        for packet in packets {
            let origin = packet.origin();
            let Some(metadata) = packet.metadata() else {
                break;
            };
            if next.is_some_and(|next| next != origin.offset) {
                break;
            }
            next = Some(origin.offset + origin.length);
            seen.insert(metadata.hash());
            run.push(metadata.to_bytes());
        }
        if seen == metadata_hashes {
            metadata = Some(run);
            break;
        }
    }
    let metadata = metadata.ok_or(EngineError::Unsupported(
        "no region holds a complete metadata run",
    ))?;
    let metadata_bytes: u64 = metadata.iter().map(|packet| packet.len() as u64).sum();
    // Host order is the File packet order of the run.
    let mut order = Vec::new();
    for bytes in &metadata {
        let hash: Fingerprint = bytes[8..24].try_into().expect("packet hash");
        if let Some(file) = layout
            .files()
            .iter()
            .position(|file| file.packet_hash == hash)
            && !order.contains(&file)
        {
            order.push(file);
        }
    }
    if order.len() != layout.files().len() {
        return Err(EngineError::Unsupported(
            "File packets are not in the metadata run",
        ));
    }
    // Gaps and region layout.
    let packet = block_size + RECOVERY_OVERHEAD;
    let mut region_layout = None;
    let mut hosts = Vec::new();
    for &file in &order {
        let entry = &layout.files()[file];
        let mut gaps = (0..entry.extents.len())
            .filter(|index| entry.extents.is_unprotected(*index))
            .filter_map(|index| entry.extents.range(index));
        let gap = gaps
            .next()
            .ok_or(EngineError::Unsupported("host has no region"))?;
        if gaps.next().is_some() {
            return Err(EngineError::Unsupported("host has more than one region"));
        }
        let length = gap.end - gap.start;
        let mut solved = None;
        for candidate in [Rar5Layout::Trailing, Rar5Layout::Block, Rar5Layout::Service] {
            if gap.end == entry.len && candidate != Rar5Layout::Trailing {
                continue;
            }
            if gap.end != entry.len && candidate == Rar5Layout::Trailing {
                continue;
            }
            if let Some((prefix, count)) = solve(candidate, length, metadata_bytes, packet) {
                solved = Some((candidate, prefix, count));
                break;
            }
        }
        let (candidate, prefix, count) =
            solved.ok_or(EngineError::Unsupported("region length fits no layout"))?;
        if region_layout.is_some_and(|layout| layout != candidate) {
            return Err(EngineError::Unsupported(
                "hosts use different region layouts",
            ));
        }
        region_layout = Some(candidate);
        hosts.push(Rar5HostState {
            name: entry.path.clone(),
            path: None,
            matched_by: None,
            file,
            source: None,
            gap: gap.clone(),
            prefix,
            length: entry.len,
            recovery: 0..count,
            complete: false,
            unresolved: Vec::new(),
            packets_found: 0,
            packets_expected: metadata.len() as u64 + count,
            region_intact: false,
        });
    }
    let region_layout = region_layout.expect("at least one host");
    // Bind files: recorded name, then recovery indices, then volume number,
    // then a lone host and a lone file.
    // Among files of the recorded name, one carrying this set's packets wins;
    // one carrying only another set's packets is never this set's host.
    let mut used = BTreeSet::new();
    for host in &mut hosts {
        let named = |c: &&Candidate| {
            file_name(&c.path) == Some(host.name.as_str()) && !used.contains(&c.source)
        };
        let ours = |c: &&Candidate| c.packets.iter().any(|p| p.input_set_id() == id);
        let foreign = |c: &&Candidate| c.packets.iter().any(|p| p.input_set_id() != id);
        if let Some(candidate) = candidates
            .iter()
            .filter(named)
            .find(ours)
            .or_else(|| candidates.iter().filter(named).find(|c| !foreign(c)))
        {
            used.insert(candidate.source);
            host.source = Some(candidate.source);
            host.path = Some(candidate.path.clone());
            host.matched_by = Some("name");
        }
    }
    // Recovery index base from a packet found at its slot in a host bound
    // by name; without one, indices start at zero.
    let mut first = None;
    'base: for (position, host) in hosts.iter().enumerate() {
        let Some(source) = host.source else { continue };
        let candidate = candidates
            .iter()
            .find(|c| c.source == source)
            .expect("bound");
        let start = host.gap.start + host.prefix + metadata_bytes;
        let before: u64 = hosts[..position].iter().map(|host| host.recovery.end).sum();
        for packet in candidate.packets.iter().filter(|p| p.input_set_id() == id) {
            let Some(PayloadKind::Recovery { index, .. }) = packet.payload().map(|p| p.kind())
            else {
                continue;
            };
            let offset = packet.origin().offset;
            if offset >= start && (offset - start).is_multiple_of(packet_len(block_size)) {
                let slot = (offset - start) / packet_len(block_size);
                if slot < host.recovery.end && index >= before + slot {
                    first = Some(index - before - slot);
                    break 'base;
                }
            }
        }
    }
    let mut base = first.unwrap_or(0);
    for host in &mut hosts {
        let count = host.recovery.end;
        host.recovery = base..base + count;
        base += count;
    }
    for host in hosts.iter_mut().filter(|host| host.source.is_none()) {
        let by_recovery = candidates.iter().find(|c| {
            !used.contains(&c.source)
                && c.packets.iter().any(|p| {
                    p.input_set_id() == id
                        && matches!(p.payload().map(|p| p.kind()),
                            Some(PayloadKind::Recovery { index, .. }) if host.recovery.contains(&index))
                })
        });
        if let Some(candidate) = by_recovery {
            used.insert(candidate.source);
            host.source = Some(candidate.source);
            host.path = Some(candidate.path.clone());
            host.matched_by = Some("recovery indices");
        }
    }
    let volume_set = hosts.len() > 1;
    for (position, host) in hosts.iter_mut().enumerate() {
        if host.source.is_some() || !volume_set {
            continue;
        }
        let snapshot_len = |c: &Candidate| access.snapshot(c.source).ok().flatten().map(|s| s.len);
        if let Some(candidate) = candidates.iter().find(|c| {
            !used.contains(&c.source)
                && c.volume == Some(position as u64)
                && snapshot_len(c) == Some(host.length)
        }) {
            used.insert(candidate.source);
            host.source = Some(candidate.source);
            host.path = Some(candidate.path.clone());
            host.matched_by = Some("volume number");
        }
    }
    if hosts.len() == 1 && hosts[0].source.is_none() {
        let free: Vec<_> = candidates
            .iter()
            .filter(|c| {
                !used.contains(&c.source) && c.packets.iter().any(|p| p.input_set_id() == id)
            })
            .collect();
        if let [candidate] = free.as_slice() {
            hosts[0].source = Some(candidate.source);
            hosts[0].path = Some(candidate.path.clone());
            hosts[0].matched_by = Some("only file");
        }
    }
    for host in &hosts {
        if let Some(source) = host.source {
            session.bind_file(&host.name, source)?;
        }
    }
    let assessment = session.assess()?;
    let status = assessment.status;
    let lost_blocks = assessment.lost_blocks.len() as u64;
    let additional = assessment.requirements.iter().map(|r| r.additional).sum();
    let recovery_available = assessment.recovery.len() as u64;
    let files = assessment.files.clone();
    for host in &mut hosts {
        let assessed = files
            .iter()
            .find(|file| file.path == host.name)
            .ok_or(EngineError::InvalidState("assessed host"))?;
        host.complete = assessed.complete && host.source.is_some();
        host.unresolved = if host.source.is_some() {
            assessed.unresolved.clone()
        } else {
            std::iter::once(0..host.length).collect()
        };
        let Some(source) = host.source else { continue };
        let candidate = candidates
            .iter()
            .find(|c| c.source == source)
            .expect("bound");
        // One pass over the host's packets indexes them by where they sit,
        // so each expected slot is a lookup rather than a scan: a host with
        // many small recovery packets stays linear.
        let mut hashes_at = BTreeSet::new();
        let mut recovery_at = BTreeSet::new();
        for p in candidate.packets.iter().filter(|p| p.input_set_id() == id) {
            let offset = p.origin().offset;
            hashes_at.insert((offset, p.hash()));
            if let Some(PayloadKind::Recovery { index, .. }) = p.payload().map(|p| p.kind()) {
                recovery_at.insert((offset, index));
            }
        }
        let at = host.gap.start + host.prefix;
        let mut found = 0;
        let mut offset = at;
        for bytes in &metadata {
            let hash: Fingerprint = bytes[8..24].try_into().expect("hash");
            if hashes_at.contains(&(offset, hash)) {
                found += 1;
            }
            offset += bytes.len() as u64;
        }
        for index in host.recovery.clone() {
            if recovery_at.contains(&(offset, index)) {
                found += 1;
            }
            offset += packet;
        }
        host.packets_found = found;
        let snapshot = access.snapshot(source)?;
        let mut header_ok = true;
        if host.prefix != 0 {
            let expected =
                region_header(region_layout, host.gap.end - host.gap.start - host.prefix);
            let mut actual = vec![0; expected.len()];
            header_ok = read_exact_at(
                &options.diagnostics,
                access.as_ref(),
                source,
                host.gap.start,
                &mut actual,
            )
            .is_ok()
                && actual == expected;
        }
        host.region_intact = found == host.packets_expected
            && header_ok
            && snapshot.is_some_and(|snapshot| snapshot.len == host.length);
    }
    Ok(Rar5Set {
        id,
        layout: region_layout,
        hosts,
        status,
        lost_blocks,
        additional,
        recovery_available,
        session,
        metadata,
        access,
    })
}

fn packet_len(block_size: u64) -> u64 {
    block_size + RECOVERY_OVERHEAD
}

/// The region header length and recovery count that fill a gap of `gap`
/// bytes in `layout`, if any.
fn solve(layout: Rar5Layout, gap: u64, metadata: u64, packet: u64) -> Option<(u64, u64)> {
    for prefix in 0..=64u64 {
        let Some(carrier) = gap.checked_sub(prefix) else {
            break;
        };
        let Some(recovery) = carrier.checked_sub(metadata) else {
            break;
        };
        if recovery % packet != 0 {
            continue;
        }
        if region_header(layout, carrier).len() as u64 == prefix {
            return Some((prefix, recovery / packet));
        }
    }
    None
}

/// What self-repair did for one host.
#[derive(Clone, Debug)]
pub struct Rar5Repaired {
    /// Recorded host name.
    pub name: String,
    /// Output written.
    pub path: PathBuf,
    /// Protected bytes were rebuilt.
    pub data_rebuilt: bool,
    /// Recovery packets regenerated rather than copied.
    pub regenerated: usize,
    /// Whether the region is the authenticated original byte for byte.
    pub restoration: CarrierRestoration,
}

impl Rar5Set {
    /// The file name each host has now: its bound file's name, or for a
    /// missing host its recorded name under the stem the bound hosts were
    /// renamed to.
    pub fn current_names(&self) -> Vec<String> {
        let renames: Vec<(String, String)> = self
            .hosts
            .iter()
            .filter_map(|host| {
                let actual = file_name(host.path.as_deref()?)?;
                stem_change(&host.name, actual)
            })
            .collect();
        self.hosts
            .iter()
            .map(|host| {
                if let Some(actual) = host.path.as_deref().and_then(file_name) {
                    return actual.to_owned();
                }
                renames
                    .iter()
                    .find_map(|(old, new)| {
                        host.name
                            .strip_prefix(old.as_str())
                            .map(|rest| format!("{new}{rest}"))
                    })
                    .unwrap_or_else(|| host.name.clone())
            })
            .collect()
    }

    /// Hosts whose protected bytes or region are not intact.
    pub fn needs_repair(&self) -> Vec<usize> {
        (0..self.hosts.len())
            .filter(|&index| !self.hosts[index].complete || !self.hosts[index].region_intact)
            .collect()
    }

    /// Rebuild every host that needs it to `destinations[k]` (absent). Hosts
    /// that are intact are left alone and get no output.
    pub fn repair(
        &mut self,
        destinations: &[PathBuf],
        scratch_directory: &Path,
    ) -> EngineResult<Vec<Rar5Repaired>> {
        if destinations.len() != self.hosts.len() {
            return Err(EngineError::InvalidState("repair destination count"));
        }
        let needed = self.needs_repair();
        if needed.is_empty() {
            return Ok(Vec::new());
        }
        if !matches!(self.status, RepairStatus::Ready | RepairStatus::Complete) {
            return Err(EngineError::Unsupported(
                "not enough recovery data to repair",
            ));
        }
        for &index in &needed {
            if std::fs::symlink_metadata(&destinations[index]).is_ok() {
                return Err(
                    io::Error::new(io::ErrorKind::AlreadyExists, "repair output exists").into(),
                );
            }
        }
        let options = self.session.options.clone();
        let layout = self.session.layout()?.expect("layout");
        // Stage every file in layout order.
        let mut scratch = Vec::new();
        for host in 0..layout.files().len() {
            scratch.push(crate::session_repair::ScratchFile::new(
                &scratch_directory.join(format!("host-{host}")),
                &options,
            )?);
        }
        let temporaries: Vec<PathBuf> = scratch.iter().map(|file| file.path().to_owned()).collect();
        crate::session_repair::stage_embedded_files(
            &mut self.session,
            &temporaries,
            crate::session_repair::RepairDurability::Buffered,
        )?;
        let mut disk = DiskSourceAccess::with_options(options.clone());
        for (index, path) in temporaries.iter().enumerate() {
            disk.insert(SourceId(index as u64), path.clone());
        }
        let disk = Arc::new(disk);
        let mut verified = Par3RepairSession::new(self.id, disk.clone(), options.clone())?;
        for packet in self.session.input.packets().filter(|packet| {
            packet.metadata().is_some()
                || packet
                    .payload()
                    .is_some_and(|payload| matches!(payload.kind(), PayloadKind::Recovery { .. }))
        }) {
            verified.merge(packet.clone())?;
        }
        for (index, file) in layout.files().iter().enumerate() {
            verified.bind_file(&file.path, SourceId(index as u64))?;
        }
        if verified.assess()?.status != RepairStatus::Complete {
            return Err(EngineError::InvalidState("rebuilt hosts are incomplete"));
        }
        let size = options.stripe_bytes.min(64 << 10);
        let mut buffer = vec![0; size];
        // Every carrier first: writing a region into a temporary changes the
        // generation `verified` bound, so no carrier can be derived after it.
        let mut carriers = Vec::new();
        let mut markers = Vec::new();
        let mut reports_pending = Vec::new();
        let generated = (|| -> EngineResult<()> {
            for &index in &needed {
                let host = &self.hosts[index];
                let marker = crate::session_repair::ScratchFile::new(
                    &scratch_directory.join(format!("carrier-{index}")),
                    &options,
                )?;
                let carrier_path = marker.path().with_extension("carrier");
                markers.push(marker);
                let plan = CarrierPlan::derived(
                    &mut verified,
                    self.metadata.clone(),
                    host.recovery.clone(),
                )?;
                if plan.output_bytes() != host.gap.end - host.gap.start - host.prefix {
                    return Err(EngineError::InvalidState("derived region length differs"));
                }
                carriers.push(carrier_path.clone());
                reports_pending.push(plan.execute(
                    &mut verified,
                    &carrier_path,
                    scratch_directory,
                )?);
            }
            Ok(())
        })();
        let mut reports = Vec::new();
        let result = generated.and_then(|()| {
            for ((&index, carrier_path), report) in
                needed.iter().zip(&carriers).zip(reports_pending.drain(..))
            {
                let host = self.hosts[index].clone();
                let carrier_bytes = host.gap.end - host.gap.start - host.prefix;
                let output = std::fs::OpenOptions::new()
                    .write(true)
                    .open_budgeted(&temporaries[host.file], &options)?;
                output.write_all_at(host.gap.start, &region_header(self.layout, carrier_bytes))?;
                let carrier = File::open(carrier_path, &options)?;
                let mut at = 0;
                while at < carrier_bytes {
                    options.cancel.check()?;
                    let take = (carrier_bytes - at).min(size as u64) as usize;
                    let read = carrier.read_at(at, &mut buffer[..take])?;
                    if read != take {
                        return Err(EngineError::InvalidState("short carrier read"));
                    }
                    output.write_all_at(host.gap.start + host.prefix + at, &buffer[..take])?;
                    at += take as u64;
                }
                output.sync_all()?;
                drop(output);
                let proof = crate::evidence::verify_source(
                    layout.clone(),
                    host.file,
                    disk.as_ref(),
                    SourceId(host.file as u64),
                    &options,
                )?;
                if !proof.protected_complete() {
                    return Err(EngineError::InvalidState(
                        "repaired host failed verification",
                    ));
                }
                install(&temporaries[host.file], &destinations[index], &options)?;
                reports.push(Rar5Repaired {
                    name: host.name.clone(),
                    path: destinations[index].clone(),
                    data_rebuilt: !host.complete,
                    regenerated: report.recovery_packets,
                    restoration: report.restoration,
                });
            }
            Ok(())
        });
        for carrier in &carriers {
            let _ = std::fs::remove_file(carrier);
        }
        drop(markers);
        result.map(|()| reports)
    }

    /// Whether [`Self::remove`] can run: every host present and verified.
    /// Nothing is written.
    ///
    /// # Errors
    ///
    /// [`EngineError::Unsupported`] naming a missing or damaged host.
    pub fn removable(&self) -> EngineResult<()> {
        match self.hosts.iter().find(|host| !host.complete) {
            Some(host) if host.source.is_none() => Err(EngineError::Unsupported(
                "a host is missing; repair before removing",
            )),
            Some(_) => Err(EngineError::Unsupported(
                "a host is damaged; repair before removing",
            )),
            None => Ok(()),
        }
    }

    /// Write every host without its region to `destinations[k]` (absent).
    /// Every host must be present and verified; the output is checked against
    /// the fingerprint the File packet recorded for the original.
    pub fn remove(&mut self, destinations: &[PathBuf]) -> EngineResult<Vec<PathBuf>> {
        if destinations.len() != self.hosts.len() {
            return Err(EngineError::InvalidState("remove destination count"));
        }
        self.removable()?;
        let options = self.session.options.clone();
        let layout = self.session.layout()?.expect("layout");
        let size = options.stripe_bytes.min(64 << 10);
        let mut buffer = vec![0; size];
        let mut written = Vec::new();
        let mut staged = Vec::new();
        let result = (|| -> EngineResult<()> {
            for (host, destination) in self.hosts.iter().zip(destinations) {
                if std::fs::symlink_metadata(destination).is_ok() {
                    return Err(io::Error::new(
                        io::ErrorKind::AlreadyExists,
                        "remove output exists",
                    )
                    .into());
                }
                let source = host.source.expect("bound");
                let temporary = crate::session_repair::stage_path(destination, &options)?;
                staged.push(temporary.clone());
                let mut output = std::fs::OpenOptions::new()
                    .write(true)
                    .open_budgeted(&temporary, &options)?;
                let mut hash = FingerprintHasher::new();
                copy(
                    self.access.as_ref(),
                    source,
                    0..host.gap.start,
                    &mut output,
                    &mut buffer,
                    Some(&mut hash),
                    &options,
                )?;
                copy(
                    self.access.as_ref(),
                    source,
                    host.gap.end..host.length,
                    &mut output,
                    &mut buffer,
                    Some(&mut hash),
                    &options,
                )?;
                if hash.finalize() != layout.files()[host.file].fingerprint {
                    return Err(EngineError::InvalidState(
                        "stripped host differs from the original",
                    ));
                }
                output.sync_all()?;
                drop(output);
                std::fs::hard_link(&temporary, destination)?;
                written.push(destination.clone());
            }
            Ok(())
        })();
        for path in staged {
            let _ = std::fs::remove_file(path);
        }
        result.map(|()| written)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn stem_changes_split_on_character_boundaries() {
        // `é` (C3 A9) and `ĩ` (C4 A9) share their last byte.
        assert_eq!(
            stem_change("host-\u{e9}.rar", "host-\u{129}.rar"),
            Some(("host-\u{e9}".to_owned(), "host-\u{129}".to_owned()))
        );
        assert_eq!(
            stem_change("old.part1.rar", "new.part1.rar"),
            Some(("old".to_owned(), "new".to_owned()))
        );
        assert_eq!(stem_change("same.rar", "same.rar"), None);
        assert_eq!(stem_change("\u{e9}", "\u{129}"), None);
    }

    /// Across filesystems a repaired host is copied beside its destination,
    /// compared, then linked in; an existing destination is never replaced.
    #[test]
    fn hosts_install_by_verified_copy() {
        let dir = std::env::temp_dir().join(format!("par3-install-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let temporary = dir.join("rebuilt");
        let contents: Vec<u8> = (0..200_000u32).map(|value| (value * 7) as u8).collect();
        std::fs::write(&temporary, &contents).unwrap();
        let options = ExecutionOptions {
            stripe_bytes: 4096,
            ..ExecutionOptions::default()
        };
        let destination = dir.join("host.rar");
        install_by_copy(&temporary, &destination, &options).unwrap();
        assert_eq!(std::fs::read(&destination).unwrap(), contents);
        assert!(install_by_copy(&temporary, &destination, &options).is_err());
        let mut names: Vec<_> = std::fs::read_dir(&dir)
            .unwrap()
            .map(|entry| entry.unwrap().file_name())
            .collect();
        names.sort();
        assert_eq!(names, ["host.rar", "rebuilt"], "no staged copy is left");
        std::fs::remove_dir_all(&dir).unwrap();
    }
}
