package fleet

import (
	"fmt"
	"strings"
)

// RemoteLayout is the on-host directory contract shared by the generated run
// script, the collector, and the resume path.
type RemoteLayout struct {
	Base    string // <staging>/<run-id>
	Bin     string // bundle binaries
	Results string // evidence, tarred at the end
	Scratch string // fast staging for timed passes (tmpfs where available)
	Tarball string
	Done    string
	Log     string
	Script  string
}

func LayoutFor(machine Machine, runID string) RemoteLayout {
	base := joinPosix(machine.Paths.Staging, runID)
	scratch := joinPosix(base, "work")
	if machine.Paths.Scratch != "" {
		scratch = joinPosix(machine.Paths.Scratch, runID)
	}
	return RemoteLayout{
		Base:    base,
		Bin:     joinPosix(base, "bin"),
		Results: joinPosix(base, "results"),
		Scratch: scratch,
		Tarball: joinPosix(base, "results.tar.gz"),
		Done:    joinPosix(base, "DONE"),
		Log:     joinPosix(base, "run.log"),
		Script:  joinPosix(base, "run.sh"),
	}
}

// RunScript builds the self-contained POSIX shell script that executes the
// whole protocol on one host with no further orchestrator interaction:
// load gate -> warmup pass -> timed repeats -> perf diagnostic pass -> tarball
// + inventory manifest + DONE sentinel.
//
// It is POSIX sh on purpose (DSM-class appliances have no bash), and it never
// interpolates orchestrator state beyond the values quoted here.
func RunScript(machine Machine, defaults RunDefaults, runID string, layout RemoteLayout, oracles map[string]string) string {
	var script strings.Builder
	write := func(format string, args ...any) {
		fmt.Fprintf(&script, format+"\n", args...)
	}

	families := machine.families()
	threshold := machine.Run.QuietLoadThreshold
	if threshold <= 0 {
		threshold = defaults.QuietLoadThreshold
	}

	write("#!/bin/sh")
	write("# Generated by rarpar-bench fleet for machine %s (%s).", machine.Name, machine.PlatformLabel)
	write("# Self-contained: once started it needs no orchestrator interaction.")
	write("set -u")
	write("RUN_ID=%s", shellQuote(runID))
	write("BASE=%s", shellQuote(layout.Base))
	write("BIN=%s", shellQuote(layout.Bin))
	write("R=%s", shellQuote(layout.Results))
	write("W=%s", shellQuote(layout.Scratch))
	write("MACHINE=%s", shellQuote(machine.PlatformLabel))
	write("CORPUS=%s", shellQuote(machine.Paths.Corpus))
	corpusSentinel := ""
	if machine.EC2 != nil && machine.EC2.CorpusSource != "" {
		corpusSentinel = joinPosix(layout.Base, "CORPUS-UPLOADED")
	}
	write("CORPUS_READY=%s", shellQuote(corpusSentinel))
	write("BENCH=\"$BIN/rarpar-bench\"")
	write("CANDIDATE=\"$BIN/rarpar\"")
	write("ORACLE_RAR=%s", shellQuote(oracles["rar"]))
	write("ORACLE_PAR2=%s", shellQuote(oracles["par2"]))
	write("SEED=%s", shellQuote(defaults.Seed))
	write("LANE=%s", shellQuote(defaults.Lane))
	write("PLACEMENT=%s", shellQuote(defaults.Par2Placement))
	write("WARMUPS=%d", machine.Run.Warmups)
	write("REPEATS=%d", machine.Run.Repeats)
	write("PERF_REPEATS=%d", machine.Perf.StatRepeats)
	write("PERF_FREQ=%d", machine.Perf.RecordFrequency)
	write("LOAD_MAX=%s", shellQuote(trimFloat(threshold)))
	write("LOAD_POLL=%d", defaults.QuietLoadPollSeconds)
	write("LOAD_CAP=%d", defaults.QuietLoadTimeoutSeconds)
	write("CASE_FILTER=%s", shellQuote(strings.Join(machine.Run.Cases, " ")))
	write("RECORD_CASES=%s", shellQuote(strings.Join(machine.Perf.RecordCases, " ")))
	write("GHZ=%s", shellQuote(trimFloat(machine.Run.Ghz)))
	write("STARTED=$(date -u +%%Y-%%m-%%dT%%H:%%M:%%SZ)")
	write("START_EPOCH=$(date +%%s)")
	write("STATUS=ok")
	write("FAILURES=''")
	write("WARNINGS=''")
	write("export RARPAR_BENCH_WORKSPACE_ROOT=\"$BASE\"")
	write("mkdir -p \"$R\" \"$W\" \"$R/perf\"")
	write("")
	// Escaped for the fmt-based writer: every literal percent in a generated
	// line has to be doubled or it silently becomes a format verb.
	write(`log() { echo "[$(date -u +%%Y-%%m-%%dT%%H:%%M:%%SZ)] $*"; }`)
	write(`fail() { STATUS=failed; FAILURES="$FAILURES $1"; log "FAILURE: $1"; }`)
	// A diagnostic pass that cannot run does not invalidate the timed evidence,
	// so it is recorded separately rather than failing the host. Hybrid-CPU perf
	// output, for instance, defeats the harness's perf-stat parser while the
	// measurements themselves are perfectly good.
	write(`warn() { WARNINGS="$WARNINGS $1"; log "WARNING: $1"; }`)
	write("")
	write("# sha256 helper: coreutils on Linux, shasum on BSD-class userlands.")
	write(`if command -v sha256sum >/dev/null 2>&1; then HASH="sha256sum"; elif command -v shasum >/dev/null 2>&1; then HASH="shasum -a 256"; else HASH=""; fi`)
	write("")

	// ---- load gate -------------------------------------------------------
	write("# Quiet-load gate. Two independent checks, because either alone lies:")
	write("#  - a process-name check catches another operator's bench mid-flight")
	write("#    before loadavg has caught up;")
	write("#  - loadavg catches background housekeeping that owns no matching name.")
	if machine.Capabilities.NoPgrep {
		write("# This host has no pgrep (busybox-class userland), so the name check uses")
		write("# ps -ef | grep with self-exclusion.")
	}
	write("gate() {")
	write("  what=\"$1\"; waited=0; loadwaited=0")
	write("  while : ; do")
	write("    busy=''")
	write("    for n in %s; do", strings.Join(defaults.QuietLoadProcessNames, " "))
	if machine.Capabilities.NoPgrep {
		write("      if ps -ef | grep \"$n\" | grep -v grep | grep -v \"$RUN_ID\" >/dev/null 2>&1; then busy=\"$busy $n\"; fi")
	} else {
		write("      if pgrep -f \"$n\" 2>/dev/null | grep -v \"^$$\\$\" >/dev/null 2>&1; then busy=\"$busy $n\"; fi")
	}
	write("    done")
	write("    if [ -n \"$busy\" ]; then")
	write("      log \"GATE $what: bench process(es) running:$busy — waiting ${LOAD_POLL}s (waited ${waited}s)\"")
	write("      sleep \"$LOAD_POLL\"; waited=$((waited + LOAD_POLL)); loadwaited=0; continue")
	write("    fi")
	write("    one=$(cut -d' ' -f1 /proc/loadavg 2>/dev/null || echo 0)")
	write("    if awk \"BEGIN { exit !($one < $LOAD_MAX) }\"; then")
	write("      log \"GATE $what: clear (loadavg1=$one, waited ${waited}s)\"; return 0")
	write("    fi")
	write("    if [ \"$loadwaited\" -ge \"$LOAD_CAP\" ]; then")
	write("      log \"GATE $what: PROCEEDING with loadavg1=$one after ${loadwaited}s (idle-baseline cap)\"; return 0")
	write("    fi")
	write("    log \"GATE $what: loadavg1=$one >= $LOAD_MAX, waiting ${LOAD_POLL}s\"")
	write("    sleep \"$LOAD_POLL\"; waited=$((waited + LOAD_POLL)); loadwaited=$((loadwaited + LOAD_POLL))")
	write("  done")
	write("}")
	write("")

	// ---- fingerprint -----------------------------------------------------
	write("log \"FLEET RUN $RUN_ID machine=$MACHINE start=$STARTED\"")
	write("{")
	write("  echo '==== date (UTC) ===='; date -u")
	write("  echo; echo '==== uname -a ===='; uname -a")
	write("  echo; echo '==== os-release ===='; cat /etc/os-release 2>/dev/null")
	write("  echo; echo '==== cpu ===='; (lscpu 2>/dev/null || cat /proc/cpuinfo 2>/dev/null || sysctl -n machdep.cpu.brand_string 2>/dev/null)")
	write("  echo; echo '==== nproc / memory ===='; (nproc 2>/dev/null || echo unknown); (free -m 2>/dev/null || true)")
	write("  echo; echo '==== loadavg ===='; cat /proc/loadavg 2>/dev/null || uptime")
	write("  echo; echo '==== mounts ===='; df -h / \"$W\" 2>/dev/null")
	write("  echo; echo '==== cpufreq ===='; for f in /sys/devices/system/cpu/cpu0/cpufreq/*; do [ -r \"$f\" ] && echo \"$f = $(cat \"$f\" 2>/dev/null)\"; done 2>/dev/null")
	write("} > \"$R/environment.txt\" 2>&1")
	write("{")
	write("  echo '==== shipped binaries ===='; ls -la \"$BIN\"")
	write("  [ -n \"$HASH\" ] && (cd \"$BIN\" && $HASH * 2>/dev/null)")
	write("  echo; echo '==== candidate ===='; \"$CANDIDATE\" --version 2>&1 | head -3")
	write("  [ -n \"$ORACLE_RAR\" ] && { echo; echo '==== oracle rar ===='; \"$ORACLE_RAR\" 2>&1 | head -3; [ -n \"$HASH\" ] && $HASH \"$ORACLE_RAR\"; }")
	write("  [ -n \"$ORACLE_PAR2\" ] && { echo; echo '==== oracle par2 ===='; \"$ORACLE_PAR2\" --version 2>&1 | head -3; [ -n \"$HASH\" ] && $HASH \"$ORACLE_PAR2\"; }")
	write("} > \"$R/binaries.txt\" 2>&1")
	write("log 'fingerprint done'")
	write("")

	// ---- crc probe -------------------------------------------------------
	if machine.hasSuite(SuiteCRCProbe) {
		write("# ---- suite: crc-probe (dispatch attribution, not a timed comparison)")
		write("if [ -x \"$BIN/crc_probe\" ]; then")
		write("  gate crc-probe")
		write("  CRC_PROBE_GHZ=\"$GHZ\" CRC_PROBE_SECS=1.5 \"$BIN/crc_probe\" > \"$R/crc_probe.txt\" 2>&1 || fail crc-probe")
		write("  log 'crc-probe done'")
		write("else")
		write("  fail crc-probe-binary-missing")
		write("fi")
		write("")
	}

	// ---- yenc micro ------------------------------------------------------
	if machine.hasSuite(SuiteYencMicro) {
		write("# ---- suite: yenc-micro (weaver decode/searchEnd against the linked oracle)")
		write("gate yenc-micro")
		write("cat /proc/loadavg > \"$R/loadavg-before-micro.txt\" 2>/dev/null")
		write("for run in 1 2; do")
		write("  for v in serial fold; do")
		write("    for t in decode_timing searchend_timing; do")
		write("      if [ -x \"$BIN/$t-$v\" ]; then")
		write("        \"$BIN/$t-$v\" > \"$R/$t-$v-$run.txt\" 2>&1 || fail \"$t-$v\"")
		write("      elif [ -x \"$BIN/$t\" ] && [ \"$v\" = serial ]; then")
		write("        \"$BIN/$t\" > \"$R/$t-$run.txt\" 2>&1 || fail \"$t\"")
		write("      fi")
		write("    done")
		write("  done")
		write("done")
		write("cat /proc/loadavg > \"$R/loadavg-after-micro.txt\" 2>/dev/null")
		write("log 'yenc-micro done'")
		write("")
	}

	// ---- macro suites ----------------------------------------------------
	if len(families) > 0 {
		write("# ---- macro suites: the standard report.json protocol")
		write("if [ -n \"$CORPUS_READY\" ]; then")
		write("  # The corpus uploads while the candidate builds; wait for its sentinel.")
		write("  log 'waiting for the corpus upload to land'")
		write("  CORPUS_WAIT=0")
		write("  while [ ! -f \"$CORPUS_READY\" ]; do")
		write("    sleep 15")
		write("    CORPUS_WAIT=$((CORPUS_WAIT+15))")
		write("    if [ \"$CORPUS_WAIT\" -ge 3600 ]; then fail corpus-upload-timeout; break; fi")
		write("  done")
		write("fi")
		write("\"$BENCH\" corpus verify --root \"$CORPUS\" > \"$R/corpus-verify.txt\" 2>&1")
		write("if [ $? -ne 0 ]; then fail corpus-verify; fi")
		write("log \"corpus verify: $(tail -1 \"$R/corpus-verify.txt\")\"")
		write("")
		write("plan_for() {")
		write("  fam=\"$1\"; out=\"$2\"; warm=\"$3\"; reps=\"$4\"; shift 4")
		write("  set -- plan create --corpus \"$CORPUS\" --out \"$out\" --seed \"$SEED\" --lane \"$LANE\" \\")
		write("    --family \"$fam\" --par2-placement \"$PLACEMENT\" --warmups \"$warm\" --repeats \"$reps\"")
		write("  for c in $CASE_FILTER; do set -- \"$@\" --case \"$c\"; done")
		write("  \"$BENCH\" \"$@\"")
		write("}")
		write("")
		write("bench_run() {")
		write("  fam=\"$1\"; plan=\"$2\"; out=\"$3\"; tag=\"$4\"; extra=\"$5\"")
		write("  rm -rf \"$out\"")
		write("  set -- run --corpus \"$CORPUS\" --plan \"$plan\" --candidate \"$CANDIDATE\" \\")
		write("    --candidate-label rarpar --reference-label reference \\")
		write("    --out \"$out\" --machine \"$MACHINE\"")
		write("  [ -n \"$ORACLE_RAR\" ] && set -- \"$@\" --reference-rar \"$ORACLE_RAR\"")
		write("  [ -n \"$ORACLE_PAR2\" ] && set -- \"$@\" --reference-par2 \"$ORACLE_PAR2\"")
		write("  [ -n \"$extra\" ] && set -- \"$@\" $extra")
		write("  \"$BENCH\" \"$@\" > \"$R/$tag.stdout.log\" 2> \"$R/$tag.stderr.log\"")
		write("  rc=$?")
		write("  log \"$tag rc=$rc\"")
		write("  return $rc")
		write("}")
		write("")
		for _, family := range families {
			write("# --- family %s", family)
			write("PLAN=\"$W/plan-%s.json\"", family)
			if machine.Run.WarmupPass() {
				write("# Warmup pass: identical work, discarded evidence. Faults the corpus")
				write("# into page cache so repeat 1 is not measuring cold I/O.")
				write("plan_for %s \"$W/plan-warmup-%s.json\" 1 1 > \"$R/plan-warmup-%s.log\" 2>&1 || fail plan-warmup-%s", family, family, family, family)
				write("gate warmup-%s", family)
				write("bench_run %s \"$W/plan-warmup-%s.json\" \"$W/warmup-%s\" warmup-%s '' || log 'warmup pass returned non-zero (evidence discarded)'", family, family, family, family)
				write("rm -rf \"$W/warmup-%s\"", family)
			}
			write("plan_for %s \"$PLAN\" \"$WARMUPS\" \"$REPEATS\" > \"$R/plan-%s.log\" 2>&1 || fail plan-%s", family, family, family)
			write("cp \"$PLAN\" \"$R/plan-%s.json\" 2>/dev/null", family)
			write("gate %s", family)
			write("if bench_run %s \"$PLAN\" \"$W/run-%s\" run-%s ''; then", family, family, family)
			write("  cp \"$W/run-%s/raw.json\" \"$R/raw-%s.json\" 2>/dev/null || fail raw-%s-missing", family, family, family)
			write("  \"$BENCH\" report --input \"$W/run-%s/raw.json\" --out \"$R/report-%s.json\" > \"$R/report-%s.log\" 2>&1 || fail report-%s", family, family, family, family)
			write("else")
			write("  fail run-%s", family)
			write("  cp \"$W/run-%s/raw.json\" \"$R/raw-%s.json\" 2>/dev/null", family, family)
			write("fi")
			write("rm -rf \"$W/run-%s\"", family)
			write("")
		}
	}

	// ---- perf diagnostic pass -------------------------------------------
	script.WriteString(perfSection(machine, families))

	// ---- manifest, tarball, sentinel ------------------------------------
	write("# ---- inventory manifest: every artifact with size and digest, so the")
	write("# collector can prove the tarball it pulled is the tarball produced here.")
	write("FINISHED=$(date -u +%%Y-%%m-%%dT%%H:%%M:%%SZ)")
	write("ELAPSED=$(( $(date +%%s) - START_EPOCH ))")
	write("(")
	write("  cd \"$R\" || exit 1")
	write("  find . -type f ! -name 'MANIFEST.json' | sort | while IFS= read -r f; do")
	write("    b=$(wc -c < \"$f\" | tr -d ' ')")
	write("    s=''")
	write("    [ -n \"$HASH\" ] && s=$($HASH \"$f\" 2>/dev/null | cut -d' ' -f1)")
	write("    printf '    {\"path\": \"%%s\", \"bytes\": %%s, \"sha256\": \"%%s\"},\\n' \"${f#./}\" \"$b\" \"$s\"")
	write("  done > \"$W/entries.txt\"")
	write(")")
	write("{")
	write("  printf '{\\n'")
	write("  printf '  \"schema_version\": 1,\\n'")
	write("  printf '  \"run_id\": \"%%s\",\\n' \"$RUN_ID\"")
	write("  printf '  \"machine\": \"%%s\",\\n' %s", shellQuote(machine.Name))
	write("  printf '  \"platform_label\": \"%%s\",\\n' \"$MACHINE\"")
	write("  printf '  \"started_utc\": \"%%s\",\\n' \"$STARTED\"")
	write("  printf '  \"finished_utc\": \"%%s\",\\n' \"$FINISHED\"")
	write("  printf '  \"elapsed_seconds\": %%s,\\n' \"$ELAPSED\"")
	write("  printf '  \"status\": \"%%s\",\\n' \"$STATUS\"")
	write("  printf '  \"failures\": \"%%s\",\\n' \"$(echo $FAILURES)\"")
	write("  printf '  \"warnings\": \"%%s\",\\n' \"$(echo $WARNINGS)\"")
	write("  printf '  \"files\": [\\n'")
	write("  sed '$ s/,$//' \"$W/entries.txt\"")
	write("  printf '  ]\\n}\\n'")
	write("} > \"$R/MANIFEST.json\"")
	write("")
	write("tar -cf - -C \"$R\" . | gzip -6 > %s", shellQuote(layout.Tarball))
	write("TARSHA=''")
	write("[ -n \"$HASH\" ] && TARSHA=$($HASH %s | cut -d' ' -f1)", shellQuote(layout.Tarball))
	write("{")
	write("  echo \"status=$STATUS\"")
	write("  echo \"run_id=$RUN_ID\"")
	write("  echo \"machine=%s\"", machine.Name)
	write("  echo \"started_utc=$STARTED\"")
	write("  echo \"finished_utc=$FINISHED\"")
	write("  echo \"elapsed_seconds=$ELAPSED\"")
	write("  echo \"tarball=%s\"", layout.Tarball)
	write("  echo \"tarball_sha256=$TARSHA\"")
	write("  echo \"tarball_bytes=$(wc -c < %s | tr -d ' ')\"", shellQuote(layout.Tarball))
	write("  echo \"files=$(grep -c '\"path\"' \"$R/MANIFEST.json\")\"")
	write("  echo \"failures=$(echo $FAILURES)\"")
	write("  echo \"warnings=$(echo $WARNINGS)\"")
	write("} > \"$BASE/DONE.tmp\"")
	write("# Rename last: the collector treats DONE as atomic proof the tarball is complete.")
	write("mv \"$BASE/DONE.tmp\" %s", shellQuote(layout.Done))
	write("log \"RUN COMPLETE status=$STATUS elapsed=${ELAPSED}s warnings:$WARNINGS\"")
	return script.String()
}

func perfSection(machine Machine, families []string) string {
	var script strings.Builder
	write := func(format string, args ...any) { fmt.Fprintf(&script, format+"\n", args...) }

	switch machine.Capabilities.Perf {
	case PerfLinux:
		write("# ---- perf diagnostic pass (linux-perf).")
		write("# Everything a diagnosis needs is exported here so nobody has to re-run a")
		write("# host to answer a follow-up question:")
		write("#  1. perf stat counters for EVERY case and BOTH subjects, via the harness")
		write("#     --perf collector (it wraps each subject invocation in perf stat);")
		write("#  2. perf record + perf script + folded stacks on the designated heavy cases.")
		write("if command -v perf >/dev/null 2>&1; then")
		write("  perf --version > \"$R/perf/perf-version.txt\" 2>&1")
		write("  cat /proc/sys/kernel/perf_event_paranoid > \"$R/perf/perf_event_paranoid.txt\" 2>/dev/null")
		for _, family := range families {
			write("  plan_for %s \"$W/plan-perf-%s.json\" 0 \"$PERF_REPEATS\" > \"$R/perf/plan-perf-%s.log\" 2>&1 || warn plan-perf-%s", family, family, family, family)
			write("  gate perf-%s", family)
			write("  if bench_run %s \"$W/plan-perf-%s.json\" \"$W/perf-%s\" perf-run-%s '--perf'; then", family, family, family, family)
			write("    cp \"$W/perf-%s/raw.json\" \"$R/perf/raw-perf-%s.json\" 2>/dev/null", family, family)
			write("    \"$BENCH\" report --input \"$W/perf-%s/raw.json\" --out \"$R/perf/report-perf-%s.json\" > \"$R/perf/report-perf-%s.log\" 2>&1 || warn perf-report-%s", family, family, family, family)
			write("  else")
			write("    warn perf-run-%s", family)
			write("  fi")
			write("  rm -rf \"$W/perf-%s\"", family)
		}
		if len(machine.Perf.RecordCases) > 0 && len(families) > 0 {
			write("  for c in $RECORD_CASES; do")
			write("    log \"perf record case $c\"")
			write("    \"$BENCH\" plan create --corpus \"$CORPUS\" --out \"$W/plan-rec-$c.json\" --seed \"$SEED\" \\")
			write("      --lane \"$LANE\" --par2-placement \"$PLACEMENT\" --warmups 0 --repeats 1 --case \"$c\" \\")
			write("      > \"$R/perf/plan-rec-$c.log\" 2>&1 || { warn \"perf-plan-$c\"; continue; }")
			write("    gate perf-record-$c")
			write("    rm -rf \"$W/rec-$c\"")
			write("    set -- run --corpus \"$CORPUS\" --plan \"$W/plan-rec-$c.json\" --candidate \"$CANDIDATE\" \\")
			write("      --candidate-label rarpar --reference-label reference --out \"$W/rec-$c\" --machine \"$MACHINE\"")
			write("    [ -n \"$ORACLE_RAR\" ] && set -- \"$@\" --reference-rar \"$ORACLE_RAR\"")
			write("    [ -n \"$ORACLE_PAR2\" ] && set -- \"$@\" --reference-par2 \"$ORACLE_PAR2\"")
			write("    # -F is deliberately moderate: a high rate perturbs the very work")
			write("    # being profiled, and this pass runs on the same box as the timings.")
			write("    perf record -F \"$PERF_FREQ\" -g --call-graph fp -o \"$W/perf-$c.data\" -- \\")
			write("      \"$BENCH\" \"$@\" > \"$R/perf/record-$c.log\" 2>&1 || warn \"perf-record-$c\"")
			write("    perf script -i \"$W/perf-$c.data\" > \"$W/perf-$c.script\" 2>>\"$R/perf/record-$c.log\" || warn \"perf-script-$c\"")
			write("    gzip -6 -c \"$W/perf-$c.script\" > \"$R/perf/perf-$c.script.gz\" 2>/dev/null")
			write("    # Stack folding inline (no stackcollapse-perf on bench hosts).")
			write("    awk '")
			write("      function flush() { if (stack != \"\") { print comm \";\" stack } stack=\"\" }")
			write("      /^$/ { flush(); next }")
			write("      /^[^ \\t]/ { flush(); comm=$1; next }")
			write("      # Strip the +0xNN offset: otherwise every return address inside one")
			write("      # function folds to its own stack and the profile is unreadable.")
			write("      { f=$2; if (f == \"\") next; sub(/\\+0x[0-9a-fA-F]+$/, \"\", f); stack = (stack == \"\" ? f : f \";\" stack) }")
			write("      END { flush() }' \"$W/perf-$c.script\" | sort | uniq -c | sort -rn \\")
			write("      | awk '{ n=$1; $1=\"\"; sub(/^ /, \"\"); print $0 \" \" n }' \\")
			write("      > \"$R/perf/perf-$c.folded\" 2>/dev/null")
			write("    perf stat -r \"$PERF_REPEATS\" -o \"$R/perf/perf-stat-$c.txt\" -- \\")
			write("      \"$BENCH\" \"$@\" > /dev/null 2>&1 || log \"perf stat -r for $c returned non-zero\"")
			write("    rm -rf \"$W/rec-$c\" \"$W/perf-$c.data\" \"$W/perf-$c.script\"")
			write("  done")
		}
		write("else")
		write("  warn perf-missing")
		write("  echo 'perf is not installed on this host' > \"$R/perf/UNAVAILABLE.txt\"")
		write("fi")
	case PerfSamply:
		write("# ---- perf diagnostic pass (samply). Same intent as the linux-perf pass:")
		write("# a sampled profile per designated heavy case, exported for later reading.")
		write("if command -v samply >/dev/null 2>&1; then")
		write("  samply --version > \"$R/perf/samply-version.txt\" 2>&1")
		write("  for c in $RECORD_CASES; do")
		write("    \"$BENCH\" plan create --corpus \"$CORPUS\" --out \"$W/plan-rec-$c.json\" --seed \"$SEED\" \\")
		write("      --lane \"$LANE\" --par2-placement \"$PLACEMENT\" --warmups 0 --repeats 1 --case \"$c\" \\")
		write("      > \"$R/perf/plan-rec-$c.log\" 2>&1 || { warn \"perf-plan-$c\"; continue; }")
		write("    gate samply-$c")
		write("    rm -rf \"$W/rec-$c\"")
		write("    set -- run --corpus \"$CORPUS\" --plan \"$W/plan-rec-$c.json\" --candidate \"$CANDIDATE\" \\")
		write("      --candidate-label rarpar --reference-label reference --out \"$W/rec-$c\" --machine \"$MACHINE\"")
		write("    [ -n \"$ORACLE_RAR\" ] && set -- \"$@\" --reference-rar \"$ORACLE_RAR\"")
		write("    [ -n \"$ORACLE_PAR2\" ] && set -- \"$@\" --reference-par2 \"$ORACLE_PAR2\"")
		write("    samply record --save-only --rate \"$PERF_FREQ\" -o \"$R/perf/samply-$c.json\" -- \\")
		write("      \"$BENCH\" \"$@\" > \"$R/perf/samply-$c.log\" 2>&1 || warn \"samply-$c\"")
		write("    gzip -6 \"$R/perf/samply-$c.json\" 2>/dev/null")
		write("    rm -rf \"$W/rec-$c\"")
		write("  done")
		write("else")
		write("  warn samply-missing")
		write("  echo 'samply is not installed on this host' > \"$R/perf/UNAVAILABLE.txt\"")
		write("fi")
	default:
		write("# ---- perf diagnostic pass: this host has no sampling collector.")
		write("# It still contributes the harness's own phase timings, which are the only")
		write("# attribution evidence available on appliance-class hosts.")
		write("echo 'capabilities.perf = none for this machine; phase timings only' > \"$R/perf/NO-COLLECTOR.txt\"")
		for _, family := range families {
			write("cp \"$R/raw-%s.json\" \"$R/perf/raw-phases-%s.json\" 2>/dev/null", family, family)
		}
	}
	write("")
	return script.String()
}

// WarmupPass reports whether an explicit discarded warmup pass runs before the
// timed repeats.
func (overrides RunOverrides) WarmupPass() bool { return !overrides.NoWarmupPass }

func joinPosix(parts ...string) string {
	cleaned := make([]string, 0, len(parts))
	for index, part := range parts {
		part = strings.TrimSuffix(part, "/")
		if index > 0 {
			part = strings.TrimPrefix(part, "/")
		}
		if part == "" {
			continue
		}
		cleaned = append(cleaned, part)
	}
	return strings.Join(cleaned, "/")
}

func trimFloat(value float64) string {
	text := fmt.Sprintf("%.3f", value)
	text = strings.TrimRight(text, "0")
	return strings.TrimSuffix(text, ".")
}
