package fleet

// Windows host runner.
//
// UNVALIDATED: this path is implemented and unit-tested against golden files
// (testdata/windows), but it has NEVER been executed against a real Windows
// host. Treat the first Windows run as bring-up, not as evidence. What is
// known-good here is the shape, not the behaviour:
//
//   - the transport (wintransport.go) needs only Windows OpenSSH and Windows
//     PowerShell 5.1: no sh, no tar. Files move by scp, directories as a zip
//     unpacked with Expand-Archive, and evidence returns as results.zip.
//   - the runner uploads a .ps1 and executes the FILE. Short control commands
//     go as -EncodedCommand (base64, so nothing to quote through cmd.exe);
//     the run itself is never an inline command string, because a script
//     quoted through ssh -> cmd.exe -> powershell truncates silently.
//   - the run starts through Win32_Process.Create, so it is not in the sshd
//     session's job object and survives the connection closing.
//   - perf is unavailable, so a Windows machine must declare
//     capabilities.perf = "none" (config validation enforces it).
//   - Defender misflags par3-rs engine_perf.exe as Trojan:Win64/AsyncRAT.C!MTB.
//     The fleet neither ships nor runs it (only a manual par3 run
//     --engine-perf does). The approved handling is a path-scoped exclusion,
//     added by hand by the host owner, on the bench work directory holding
//     engine_perf.exe. Nothing here touches Defender, and nothing may.
//
// TODO(windows): run this end to end on the dGPU box and confirm: scp accepts
// the /C:/... path form (sftp-server and legacy scp), Expand-Archive and
// ZipFile behave on the host's PowerShell/.NET, Win32_Process.Create
// detachment survives the SSH session closing, the -EncodedCommand budget is
// enough for every control script, and Get-Process name matching is a good
// enough load gate on a desktop-class host.

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func windowsLayout(machine Machine, runID string) RemoteLayout {
	base := machine.Paths.Staging + "\\" + runID
	scratch := base + "\\work"
	if machine.Paths.Scratch != "" {
		scratch = machine.Paths.Scratch + "\\" + runID
	}
	return RemoteLayout{
		Base:    base,
		Bin:     base + "\\bin",
		Results: base + "\\results",
		Scratch: scratch,
		Tarball: base + "\\results.zip",
		Done:    base + "\\DONE",
		Log:     base + "\\run.log",
		Script:  base + "\\run.ps1",
	}
}

// WindowsRunScript mirrors the POSIX protocol: gate, warmup, timed repeats,
// evidence tarball, inventory manifest, DONE sentinel. There is no perf pass.
func WindowsRunScript(machine Machine, defaults RunDefaults, runID string, layout RemoteLayout, oracles map[string]string) string {
	var script strings.Builder
	write := func(format string, args ...any) { fmt.Fprintf(&script, format+"\r\n", args...) }
	// q quotes every interpolated value as a PowerShell single-quoted literal
	// (embedded ' doubled), so no operator value is ever parsed as code.
	q := psQuote

	write("# Generated by rarpar-bench fleet. Do not edit on the host.")
	write("$ErrorActionPreference = 'Continue'")
	write("$ProgressPreference = 'SilentlyContinue'")
	write("$RunId = %s", q(runID))
	write("$MachineName = %s", q(machine.Name))
	write("$Base = %s", q(layout.Base))
	write("$Bin = %s", q(layout.Bin))
	write("$R = %s", q(layout.Results))
	write("$W = %s", q(layout.Scratch))
	write("$Machine = %s", q(machine.PlatformLabel))
	write("$Corpus = %s", q(machine.Paths.Corpus))
	write("$Zip = %s", q(layout.Tarball))
	write("$Done = %s", q(layout.Done))
	write("$Bench = Join-Path $Bin 'rarpar-bench.exe'")
	write("$Candidate = Join-Path $Bin 'rarpar.exe'")
	write("$OracleRar = %s", q(oracles["rar"]))
	write("$OraclePar2 = %s", q(oracles["par2"]))
	write("$OraclePar3 = %s", q(oracles["par3"]))
	write("$Utf8NoBom = New-Object Text.UTF8Encoding $false")
	write("$Status = 'ok'")
	write("$Failures = @()")
	write("$Started = (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')")
	write("$StartTicks = [DateTime]::UtcNow")
	write("foreach ($d in @($R, $W)) { if (-not (Test-Path -LiteralPath $d)) { New-Item -ItemType Directory -Force -Path $d | Out-Null } }")
	write("$env:RARPAR_BENCH_WORKSPACE_ROOT = $Base")
	write("function Log($m) { Write-Output (\"[{0}] {1}\" -f (Get-Date).ToUniversalTime().ToString('HH:mm:ss'), $m) }")
	write("function Fail($m) { $script:Status = 'failed'; $script:Failures += $m; Log \"FAILURE: $m\" }")
	write("function Gate($what) {")
	write("  $names = @(%s)", quotePowerShellList(defaults.QuietLoadProcessNames))
	write("  $waited = 0")
	write("  while ($true) {")
	write("    $busy = @()")
	write("    foreach ($n in $names) { if (Get-Process -Name $n -ErrorAction SilentlyContinue) { $busy += $n } }")
	write("    if ($busy.Count -eq 0) { Log \"GATE $what clear (waited ${waited}s)\"; return }")
	write("    if ($waited -ge %d) { Log \"GATE $what proceeding after ${waited}s\"; return }", defaults.QuietLoadTimeoutSeconds)
	write("    Log \"GATE $what busy: $($busy -join ',')\"")
	write("    Start-Sleep -Seconds %d; $waited += %d", defaults.QuietLoadPollSeconds, defaults.QuietLoadPollSeconds)
	write("  }")
	write("}")
	write("Get-ComputerInfo | Out-File -LiteralPath (Join-Path $R 'environment.txt') -Encoding utf8")
	write("Get-ChildItem -LiteralPath $Bin | Out-File -LiteralPath (Join-Path $R 'binaries.txt') -Encoding utf8")
	write("Get-ChildItem -LiteralPath $Bin -File | ForEach-Object { Get-FileHash -Algorithm SHA256 -LiteralPath $_.FullName } | Out-File -LiteralPath (Join-Path $R 'binaries.txt') -Append -Encoding utf8")

	if machine.hasSuite(SuiteCRCProbe) {
		write("$probe = Join-Path $Bin 'crc_probe.exe'")
		write("if (Test-Path -LiteralPath $probe) { Gate 'crc-probe'; & $probe *> (Join-Path $R 'crc_probe.txt') } else { Fail 'crc-probe-binary-missing' }")
	}
	for _, family := range machine.families() {
		write("& $Bench corpus verify --root $Corpus *> (Join-Path $R 'corpus-verify.txt')")
		write("$plan = Join-Path $W %s", q("plan-"+family+".json"))
		write("& $Bench plan create --corpus $Corpus --out $plan --seed %s --lane %s --family %s --par2-placement %s --warmups %d --repeats %d *> (Join-Path $R %s)",
			q(defaults.Seed), q(defaults.Lane), q(family), q(defaults.Par2Placement), machine.Run.Warmups, machine.Run.Repeats, q("plan-"+family+".log"))
		write("Copy-Item -LiteralPath $plan -Destination (Join-Path $R %s) -ErrorAction SilentlyContinue", q("plan-"+family+".json"))
		write("Gate %s", q(family))
		write("$out = Join-Path $W %s", q("run-"+family))
		write("if (Test-Path -LiteralPath $out) { Remove-Item -LiteralPath $out -Recurse -Force -ErrorAction SilentlyContinue }")
		write("$benchArgs = @('run','--corpus',$Corpus,'--plan',$plan,'--candidate',$Candidate,'--candidate-label','rarpar','--reference-label','reference','--out',$out,'--machine',$Machine)")
		write("if ($OracleRar) { $benchArgs += @('--reference-rar', $OracleRar) }")
		write("if ($OraclePar2) { $benchArgs += @('--reference-par2', $OraclePar2) }")
		write("& $Bench @benchArgs *> (Join-Path $R %s)", q("run-"+family+".log"))
		write("if ($LASTEXITCODE -ne 0) { Fail %s }", q("run-"+family))
		write("Copy-Item -LiteralPath (Join-Path $out 'raw.json') -Destination (Join-Path $R %s) -ErrorAction SilentlyContinue", q("raw-"+family+".json"))
		write("& $Bench report --input (Join-Path $out 'raw.json') --out (Join-Path $R %s) *> (Join-Path $R %s)", q("report-"+family+".json"), q("report-"+family+".log"))
		write("if (Test-Path -LiteralPath $out) { Remove-Item -LiteralPath $out -Recurse -Force -ErrorAction SilentlyContinue }")
	}
	if machine.hasSuite(SuiteMacroPAR3) {
		// The suite detects a Defender quarantine of either binary (errno 225/
		// 226 or a changed hash) and stops as binary-quarantined; it never
		// adds exclusions or otherwise works around Defender.
		args := make([]string, 0)
		for _, arg := range par3Args(machine) {
			args = append(args, q(arg))
		}
		write("$p3Work = %s", q(PAR3Work(machine, layout)))
		write("if (Test-Path -LiteralPath $OraclePar3) {")
		write("  Gate 'macro-par3'")
		write("  $p3Args = @('par3','run','--reference',$OraclePar3,'--candidate',$Candidate,'--work',$p3Work,'--out',(Join-Path $R 'par3'),'--machine',$Machine,%s)", strings.Join(args, ","))
		write("  & $Bench @p3Args *> (Join-Path $R 'par3-run.log')")
		write("  if ($LASTEXITCODE -ne 0) { Fail 'macro-par3' }")
		write("} else { Fail 'par3-reference-missing' }")
		write("if (Test-Path -LiteralPath $p3Work) { Remove-Item -LiteralPath $p3Work -Recurse -Force -ErrorAction SilentlyContinue }")
	}
	write("[IO.File]::WriteAllText((Join-Path $R 'perf-NO-COLLECTOR.txt'), \"capabilities.perf = none on Windows hosts; phase timings only`r`n\", $Utf8NoBom)")
	write("$Finished = (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')")
	write("$Elapsed = [int]([DateTime]::UtcNow - $StartTicks).TotalSeconds")
	write("$files = Get-ChildItem -LiteralPath $R -Recurse -File | Where-Object { $_.Name -ne 'MANIFEST.json' } | ForEach-Object {")
	write("  [ordered]@{ path = $_.FullName.Substring($R.Length + 1).Replace('\\','/'); bytes = $_.Length; sha256 = (Get-FileHash -Algorithm SHA256 -LiteralPath $_.FullName).Hash.ToLower() } }")
	write("$manifest = [ordered]@{ schema_version = 1; run_id = $RunId; machine = $MachineName; platform_label = $Machine; started_utc = $Started; finished_utc = $Finished; elapsed_seconds = $Elapsed; status = $Status; failures = ($Failures -join ' '); files = @($files) }")
	// Out-File -Encoding utf8 writes a BOM on Windows PowerShell 5.1, which
	// encoding/json rejects; write UTF-8 without one.
	write("[IO.File]::WriteAllText((Join-Path $R 'MANIFEST.json'), ($manifest | ConvertTo-Json -Depth 5), $Utf8NoBom)")
	write("Add-Type -AssemblyName System.IO.Compression.FileSystem")
	write("if (Test-Path -LiteralPath $Zip) { Remove-Item -LiteralPath $Zip -Force }")
	write("[IO.Compression.ZipFile]::CreateFromDirectory($R, $Zip)")
	write("$zipHash = (Get-FileHash -Algorithm SHA256 -LiteralPath $Zip).Hash.ToLower()")
	write("$zipBytes = (Get-Item -LiteralPath $Zip).Length")
	write("$sentinel = @(('status=' + $Status), ('run_id=' + $RunId), ('machine=' + $MachineName), ('started_utc=' + $Started), ('finished_utc=' + $Finished), ('elapsed_seconds=' + $Elapsed), ('tarball=' + $Zip), ('tarball_sha256=' + $zipHash), ('tarball_bytes=' + $zipBytes), ('files=' + @($files).Count), ('failures=' + ($Failures -join ' '))) -join \"`r`n\"")
	write("[IO.File]::WriteAllText(($Done + '.tmp'), ($sentinel + \"`r`n\"), $Utf8NoBom)")
	write("Move-Item -LiteralPath ($Done + '.tmp') -Destination $Done -Force")
	write("Log \"RUN COMPLETE status=$Status elapsed=${Elapsed}s\"")
	return script.String()
}

func quotePowerShellList(values []string) string {
	quoted := make([]string, 0, len(values))
	for _, value := range values {
		quoted = append(quoted, psQuote(value))
	}
	return strings.Join(quoted, ",")
}

func (orch *orchestrator) runWindows(ctx context.Context, machine Machine, hostState *MachineState) error {
	orch.log("machine %s: WINDOWS RUNNER IS UNVALIDATED — treat this host's first run as bring-up, not evidence", machine.Name)
	orch.state.Record(hostState, "spawn", "windows runner is unvalidated; see internal/fleet/windows.go")
	orch.state.SetStatus(hostState, StatusSpawning)

	transport, err := NewTransport(machine, orch.runDir)
	if err != nil {
		return err
	}
	defer transport.Close()

	layout := windowsLayout(machine, orch.options.RunID)
	hostState.Remote = layout
	oracleTargets := map[string]string{}
	for role, resolution := range hostState.Oracles {
		oracleTargets[role] = resolution.RemotePath
	}
	script := WindowsRunScript(machine, orch.options.Config.Fleet.Defaults, orch.options.RunID, layout, oracleTargets)
	upload := filepath.Join(orch.runDir, "upload-"+machine.Name)
	if err := os.MkdirAll(upload, 0o755); err != nil {
		return err
	}
	// A UTF-8 BOM, or Windows PowerShell 5.1 reads the file as ANSI.
	scriptBytes := append([]byte("\ufeff"), script...)
	if err := os.WriteFile(filepath.Join(upload, "run.ps1"), scriptBytes, 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(orch.runDir, "run-"+machine.Name+".ps1"), scriptBytes, 0o644); err != nil {
		return err
	}
	if err := transport.UploadDir(ctx, hostState.BundleDir, layout.Bin); err != nil {
		return err
	}
	if err := transport.UploadDir(ctx, upload, layout.Base); err != nil {
		return err
	}
	// Execute the FILE, detached from the SSH session. The run is never an
	// inline command string.
	stdout, _, err := transport.RunPowerShell(ctx, psStartDetachedScript(layout.Script, layout.Log, layout.Base))
	if err != nil {
		return fmt.Errorf("machine %s: starting the PowerShell runner: %w", machine.Name, err)
	}
	orch.state.Record(hostState, "start", "run.ps1 started detached (%s)", strings.TrimSpace(stdout))
	orch.state.SetStatus(hostState, StatusRunning)
	return orch.collectMachine(ctx, machine, hostState)
}
