package fleet

// Windows (SYLIX-class) host runner.
//
// UNVALIDATED: this path is schema-complete and implemented, but it has never
// been executed against a real Windows host. Treat the first Windows run as a
// bring-up, not as evidence. What is known-good here is the shape, not the
// behaviour:
//
//   - the runner uploads a .ps1 and executes the FILE. PowerShell is never
//     driven by an inline command string: quoting a script through ssh ->
//     cmd.exe -> powershell has burned entire sessions, and the failure mode is
//     a silently truncated script rather than an error.
//   - perf is unavailable, so a Windows machine must declare
//     capabilities.perf = "none" (config validation enforces it).
//
// TODO(windows): run this end to end on the RTX/Ryzen box, confirm tar.exe is
// present (Windows 10 1803+ ships bsdtar), confirm Start-Process detachment
// survives the SSH session closing, and confirm Get-Process name matching is a
// good enough load gate on a desktop-class host.

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func windowsLayout(machine Machine, runID string) RemoteLayout {
	base := machine.Paths.Staging + "\\" + runID
	scratch := base + "\\work"
	if machine.Paths.Scratch != "" {
		scratch = machine.Paths.Scratch + "\\" + runID
	}
	return RemoteLayout{
		Base:    base,
		Bin:     base + "\\bin",
		Results: base + "\\results",
		Scratch: scratch,
		Tarball: base + "\\results.tar.gz",
		Done:    base + "\\DONE",
		Log:     base + "\\run.log",
		Script:  base + "\\run.ps1",
	}
}

// WindowsRunScript mirrors the POSIX protocol: gate, warmup, timed repeats,
// evidence tarball, inventory manifest, DONE sentinel. There is no perf pass.
func WindowsRunScript(machine Machine, defaults RunDefaults, runID string, layout RemoteLayout, oracles map[string]string) string {
	var script strings.Builder
	write := func(format string, args ...any) { fmt.Fprintf(&script, format+"\r\n", args...) }

	write("# Generated by rarpar-bench fleet for %s (%s). Do not edit on the host.", machine.Name, machine.PlatformLabel)
	write("$ErrorActionPreference = 'Continue'")
	write("$RunId = '%s'", runID)
	write("$Base = '%s'", layout.Base)
	write("$Bin = '%s'", layout.Bin)
	write("$R = '%s'", layout.Results)
	write("$W = '%s'", layout.Scratch)
	write("$Machine = '%s'", machine.PlatformLabel)
	write("$Corpus = '%s'", machine.Paths.Corpus)
	write("$Bench = Join-Path $Bin 'rarpar-bench.exe'")
	write("$Candidate = Join-Path $Bin 'rarpar.exe'")
	write("$OracleRar = '%s'", oracles["rar"])
	write("$OraclePar2 = '%s'", oracles["par2"])
	write("$Status = 'ok'")
	write("$Failures = @()")
	write("$Started = (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')")
	write("$StartTicks = [DateTime]::UtcNow")
	write("New-Item -ItemType Directory -Force -Path $R, $W | Out-Null")
	write("$env:RARPAR_BENCH_WORKSPACE_ROOT = $Base")
	write("function Log($m) { Write-Output (\"[{0}] {1}\" -f (Get-Date).ToUniversalTime().ToString('HH:mm:ss'), $m) }")
	write("function Fail($m) { $script:Status = 'failed'; $script:Failures += $m; Log \"FAILURE: $m\" }")
	write("function Gate($what) {")
	write("  $names = @(%s)", quotePowerShellList(defaults.QuietLoadProcessNames))
	write("  $waited = 0")
	write("  while ($true) {")
	write("    $busy = @()")
	write("    foreach ($n in $names) { if (Get-Process -Name $n -ErrorAction SilentlyContinue) { $busy += $n } }")
	write("    if ($busy.Count -eq 0) { Log \"GATE $what clear (waited ${waited}s)\"; return }")
	write("    if ($waited -ge %d) { Log \"GATE $what proceeding after ${waited}s\"; return }", defaults.QuietLoadTimeoutSeconds)
	write("    Log \"GATE $what busy: $($busy -join ',')\"")
	write("    Start-Sleep -Seconds %d; $waited += %d", defaults.QuietLoadPollSeconds, defaults.QuietLoadPollSeconds)
	write("  }")
	write("}")
	write("Get-ComputerInfo | Out-File -FilePath (Join-Path $R 'environment.txt') -Encoding utf8")
	write("Get-ChildItem $Bin | Out-File -FilePath (Join-Path $R 'binaries.txt') -Encoding utf8")
	write("Get-FileHash -Algorithm SHA256 (Get-ChildItem $Bin -File).FullName | Out-File -Append -FilePath (Join-Path $R 'binaries.txt') -Encoding utf8")

	if machine.hasSuite(SuiteCRCProbe) {
		write("$probe = Join-Path $Bin 'crc_probe.exe'")
		write("if (Test-Path $probe) { Gate 'crc-probe'; & $probe *> (Join-Path $R 'crc_probe.txt') } else { Fail 'crc-probe-binary-missing' }")
	}
	for _, family := range machine.families() {
		write("& $Bench corpus verify --root $Corpus *> (Join-Path $R 'corpus-verify.txt')")
		write("$plan = Join-Path $W 'plan-%s.json'", family)
		write("& $Bench plan create --corpus $Corpus --out $plan --seed '%s' --lane '%s' --family '%s' --par2-placement '%s' --warmups %d --repeats %d *> (Join-Path $R 'plan-%s.log')",
			defaults.Seed, defaults.Lane, family, defaults.Par2Placement, machine.Run.Warmups, machine.Run.Repeats, family)
		write("Copy-Item $plan (Join-Path $R 'plan-%s.json') -ErrorAction SilentlyContinue", family)
		write("Gate '%s'", family)
		write("$out = Join-Path $W 'run-%s'", family)
		write("Remove-Item -Recurse -Force $out -ErrorAction SilentlyContinue")
		write("$benchArgs = @('run','--corpus',$Corpus,'--plan',$plan,'--candidate',$Candidate,'--candidate-label','rarpar','--reference-label','reference','--out',$out,'--machine',$Machine)")
		write("if ($OracleRar) { $benchArgs += @('--reference-rar', $OracleRar) }")
		write("if ($OraclePar2) { $benchArgs += @('--reference-par2', $OraclePar2) }")
		write("& $Bench @benchArgs *> (Join-Path $R 'run-%s.log')", family)
		write("if ($LASTEXITCODE -ne 0) { Fail 'run-%s' }", family)
		write("Copy-Item (Join-Path $out 'raw.json') (Join-Path $R 'raw-%s.json') -ErrorAction SilentlyContinue", family)
		write("& $Bench report --input (Join-Path $out 'raw.json') --out (Join-Path $R 'report-%s.json') *> (Join-Path $R 'report-%s.log')", family, family)
		write("Remove-Item -Recurse -Force $out -ErrorAction SilentlyContinue")
	}
	write("'capabilities.perf = none on Windows hosts; phase timings only' | Out-File -FilePath (Join-Path $R 'perf-NO-COLLECTOR.txt') -Encoding utf8")
	write("$Finished = (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')")
	write("$Elapsed = [int]([DateTime]::UtcNow - $StartTicks).TotalSeconds")
	write("$files = Get-ChildItem -Recurse -File $R | Where-Object { $_.Name -ne 'MANIFEST.json' } | ForEach-Object {")
	write("  [ordered]@{ path = $_.FullName.Substring($R.Length + 1).Replace('\\','/'); bytes = $_.Length; sha256 = (Get-FileHash -Algorithm SHA256 $_.FullName).Hash.ToLower() } }")
	write("$manifest = [ordered]@{ schema_version = 1; run_id = $RunId; machine = '%s'; platform_label = $Machine; started_utc = $Started; finished_utc = $Finished; elapsed_seconds = $Elapsed; status = $Status; failures = ($Failures -join ' '); files = @($files) }", machine.Name)
	write("$manifest | ConvertTo-Json -Depth 5 | Out-File -FilePath (Join-Path $R 'MANIFEST.json') -Encoding utf8")
	write("tar.exe -czf '%s' -C $R .", layout.Tarball)
	write("$tarHash = (Get-FileHash -Algorithm SHA256 '%s').Hash.ToLower()", layout.Tarball)
	write("$tarBytes = (Get-Item '%s').Length", layout.Tarball)
	write("@(\"status=$Status\", \"run_id=$RunId\", \"machine=%s\", \"started_utc=$Started\", \"finished_utc=$Finished\", \"elapsed_seconds=$Elapsed\", \"tarball=%s\", \"tarball_sha256=$tarHash\", \"tarball_bytes=$tarBytes\", \"files=$($files.Count)\", \"failures=$($Failures -join ' ')\") | Out-File -FilePath '%s.tmp' -Encoding ascii",
		machine.Name, strings.ReplaceAll(layout.Tarball, "\\", "\\\\"), layout.Done)
	write("Move-Item -Force '%s.tmp' '%s'", layout.Done, layout.Done)
	write("Log \"RUN COMPLETE status=$Status elapsed=${Elapsed}s\"")
	return script.String()
}

func quotePowerShellList(values []string) string {
	quoted := make([]string, 0, len(values))
	for _, value := range values {
		quoted = append(quoted, "'"+strings.ReplaceAll(value, "'", "''")+"'")
	}
	return strings.Join(quoted, ",")
}

func (orch *orchestrator) runWindows(ctx context.Context, machine Machine, hostState *MachineState) error {
	orch.log("machine %s: WINDOWS RUNNER IS UNVALIDATED — treat this host's first run as bring-up, not evidence", machine.Name)
	orch.state.Record(hostState, "spawn", "windows runner is unvalidated; see internal/fleet/windows.go")
	orch.state.SetStatus(hostState, StatusSpawning)

	transport, err := NewTransport(machine, orch.runDir)
	if err != nil {
		return err
	}
	transport.Shell = "sh" // OpenSSH on Windows still accepts a command string.
	defer transport.Close()

	layout := windowsLayout(machine, orch.options.RunID)
	hostState.Remote = layout
	oracleTargets := map[string]string{}
	for role, resolution := range hostState.Oracles {
		oracleTargets[role] = resolution.RemotePath
	}
	script := WindowsRunScript(machine, orch.options.Config.Fleet.Defaults, orch.options.RunID, layout, oracleTargets)
	upload := filepath.Join(orch.runDir, "upload-"+machine.Name)
	if err := os.MkdirAll(upload, 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(upload, "run.ps1"), []byte(script), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(orch.runDir, "run-"+machine.Name+".ps1"), []byte(script), 0o644); err != nil {
		return err
	}
	if err := transport.UploadDir(ctx, hostState.BundleDir, layout.Bin); err != nil {
		return err
	}
	if err := transport.UploadDir(ctx, upload, layout.Base); err != nil {
		return err
	}
	// Execute the FILE, detached. No inline PowerShell, ever.
	start := fmt.Sprintf("powershell -NoProfile -ExecutionPolicy Bypass -Command \"Start-Process powershell -ArgumentList '-NoProfile','-ExecutionPolicy','Bypass','-File','%s' -RedirectStandardOutput '%s' -WindowStyle Hidden\"",
		layout.Script, layout.Log)
	command := transport.command(ctx, start)
	if output, err := command.CombinedOutput(); err != nil {
		return fmt.Errorf("machine %s: starting the PowerShell runner: %w: %s", machine.Name, err, strings.TrimSpace(string(output)))
	}
	orch.state.SetStatus(hostState, StatusRunning)
	return orch.collectMachine(ctx, machine, hostState)
}
