#!/bin/bash
# Regenerate the stored-layout fixture sets consumed by
# tests/stored_layout_fixtures.rs.
#
# These sets exist because the rest of the corpus does not reach them: a chain
# longer than twenty volumes, a recovery record on every volume of a stored
# set, and the `-htb` BLAKE2 hash switch. Everything else those tests use is
# already checked in and generated by the sibling scripts.
#
# Requirements:
# - docker on PATH
# - local image `rar:latest` — RARLAB rar 7.20, with `rar` as ENTRYPOINT.
#   Note that 7.20 dropped `-ma4` and `-vn`, so it cannot write RAR4 archives
#   or old-style (.r00) volume names; the RAR4 sets come from `rar:4` via
#   generate_edge_cases.sh.
#
# Usage: bash crates/weaver-unrar/tests/fixtures/generate_stored_layout.sh
#
# Output is not byte-reproducible: RAR stamps archive and file times into the
# headers. The header *shapes* the tests assert are stable.
set -euo pipefail

FIXTURE_DIR="$(cd "$(dirname "$0")" && pwd)"
RAR5_DIR="$FIXTURE_DIR/rar5"
WORK="$(mktemp -d)"
cleanup() { rm -rf "$WORK"; }
trap cleanup EXIT

mkdir -p "$WORK/src" "$WORK/out" "$RAR5_DIR"

# Fixed-seed incompressible payloads. Stored members must not be shrinkable, or
# `-m0` stops being the interesting case, and fixed seeds keep the member sizes
# and split boundaries stable across regenerations.
python3 - "$WORK/src" <<'PY'
import os, random, sys
d = sys.argv[1]
def blob(name, size, seed):
    r = random.Random(seed)
    with open(os.path.join(d, name), 'wb') as f:
        f.write(bytes(r.randrange(256) for _ in range(size)))
blob('Silver.Horizon.S01E04.mkv', 48 * 1024, 4004)
blob('Silver.Horizon.S01E05.mkv', 16 * 1024, 5005)
blob('Silver.Horizon.S01E06.mkv', 4 * 1024, 6006)
blob('Silver.Horizon.S01E07.mkv', 3 * 1024, 7007)
with open(os.path.join(d, 'Silver.Horizon.S01E07.nfo'), 'w') as f:
    f.write('Silver Horizon season one, episode seven.\n')
PY

rar5() {
    docker run --rm --platform linux/amd64 -v "$WORK:/w" -w /w/src rar:latest "$@"
}

# [1/5] Long chain: 48 KiB across 2 KiB volumes -> 27 parts. The first part is
# one byte larger than the middle ones and the last is much smaller, so a
# prefix sum over the chain cannot be mistaken for `index * part_size`.
rar5 a -idq -m0 -v2k ../out/rar5_mv_store_long.rar Silver.Horizon.S01E04.mkv

# [2/5] Recovery record on every volume of a stored multi-volume set: RR
# service data that must land in the envelope without disturbing the member
# mapping. 16 KiB across 4 KiB volumes -> 6 parts.
rar5 a -idq -m0 -rr5p -v4k ../out/rar5_mv_store_rr.rar Silver.Horizon.S01E05.mkv

# [3/5] BLAKE2 across a split chain: non-final parts state a packed BLAKE2sp
# and no packed CRC32. 4 KiB across 1 KiB volumes -> 6 parts.
rar5 a -idq -m0 -htb -v1k ../out/rar5_mv_store_blake2.rar Silver.Horizon.S01E06.mkv

# [4/5] and [5/5] The BLAKE2 pair: identical members and layout, differing only
# in the hash switch. Together they establish that `-htb` replaces the CRC32
# rather than adding to it.
rar5 a -idq -m0 -htb ../out/rar5_store_blake2.rar \
    Silver.Horizon.S01E07.mkv Silver.Horizon.S01E07.nfo
rar5 a -idq -m0 ../out/rar5_store_crc32_control.rar \
    Silver.Horizon.S01E07.mkv Silver.Horizon.S01E07.nfo

rm -f "$RAR5_DIR"/rar5_mv_store_long.part*.rar \
      "$RAR5_DIR"/rar5_mv_store_rr.part*.rar \
      "$RAR5_DIR"/rar5_mv_store_blake2.part*.rar \
      "$RAR5_DIR"/rar5_store_blake2.rar \
      "$RAR5_DIR"/rar5_store_crc32_control.rar
cp "$WORK"/out/*.rar "$RAR5_DIR/"
chmod 444 "$WORK"/out/*.rar 2>/dev/null || true

echo "Generated stored-layout fixtures into $RAR5_DIR:"
ls -1 "$WORK/out"
