name: ClusterFuzzLite batch fuzzing

on:
  schedule:
    - cron: '41 2 * * 0'
  workflow_dispatch:

permissions: read-all

jobs:
  batch-fuzzing:
    runs-on: ubuntu-24.04
    timeout-minutes: 75
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Build fuzzers
        id: build
        uses: google/clusterfuzzlite/actions/build_fuzzers@82652fb49e77bc29c35da1167bb286e93c6bcc05 # v1
        with:
          language: rust

      - name: Run fuzzers
        uses: google/clusterfuzzlite/actions/run_fuzzers@82652fb49e77bc29c35da1167bb286e93c6bcc05 # v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 3600
          mode: batch
          sanitizer: address
